pub const INIT_MIGRATION: &str = concat!(
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/001_initial.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/002_add_leader_tips.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/003_add_sync_state.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/004_add_leader_allowlist.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/005_add_policy_bundles.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/006_add_policy_bundle_versions.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/007_add_tokens.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/008_add_audit_log.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/009_add_audit_log_hash_chain.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/010_add_agent_registry.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/011_add_audit_merkle_roots.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/012_add_audit_checkpoints.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/013_add_lifecycle_outbox.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/014_add_lifecycle_outbox_fencing.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/015_add_mfa_credentials.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/016_add_mfa_credentials_active_index.sql"
    )),
    "\n",
    include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/migrations/017_add_mfa_lockout_columns.sql"
    )),
);

/// Current schema version for the SQLite embedded migration.
pub const CURRENT_SCHEMA_VERSION: i64 = 17;
