#!/usr/bin/env python3
"""generate_perf_baselines.py — Generate baseline JSON files from ferrum-stress output.

Usage:
    python3 scripts/generate_perf_baselines.py \
        --stress-json /tmp/ferrum-stress.json \
        --output-dir baselines/ \
        [--duration 5] \
        [--promote-authoritative]

Generated baselines are SAMPLE / NON-AUTHORITATIVE by default. Use
--promote-authoritative only when you have a validated, controlled run and
intend to make the gate blocking. The authoritative promotion metadata must
include a real commit SHA; PERF_BASELINE_AUTHORITATIVE_AT is optional and
defaults to the current UTC time.

Environment variables:
    PERF_BASELINE_AUTHORITATIVE_COMMIT  — required when --promote-authoritative
    PERF_BASELINE_AUTHORITATIVE_AT      — optional ISO 8601 timestamp (default: now)
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import re
import sys
from pathlib import Path
from typing import Any


DEFAULT_DURATION_SECS = 5


def _normalize_scenario_name(name: str) -> str:
    """Return a filesystem-friendly scenario name using underscores."""
    # Match existing baselines/ convention: sample_<scenario>_5s.json
    return re.sub(r"[^a-zA-Z0-9_\-]+", "_", name).replace("-", "_").strip("_")


def _build_metric_spec(metric_name: str, actual: float) -> dict[str, Any]:
    """Build a baseline metric spec with conservative default thresholds."""
    spec: dict[str, Any] = {"baseline": actual, "unit": ""}

    # Latency metrics (lower is better)
    if metric_name in ("p95_ms", "p99_ms", "p50_ms", "mean_ms"):
        spec["unit"] = "ms"
        spec["max_ratio"] = 2.50
        return spec

    # Throughput metrics (higher is better)
    if metric_name == "req_per_sec":
        spec["unit"] = "req/s"
        spec["min_ratio"] = 0.70
        return spec

    # Error rate (hard cap)
    if metric_name == "error_rate":
        spec["unit"] = "ratio"
        spec["max_absolute"] = 0.01
        return spec

    # Generic fallback with 10% tolerance
    spec["max_ratio"] = 1.10
    return spec


def _build_metrics(scenario: dict[str, Any]) -> dict[str, Any]:
    """Build metric specs from a stress scenario result.

    Only includes well-known metric keys that appear in stress output. Unknown
    keys are ignored to keep the baseline schema stable.
    """
    metrics: dict[str, Any] = {}
    for metric_name in ("req_per_sec", "p95_ms", "p99_ms", "p50_ms", "mean_ms", "error_rate"):
        actual = scenario.get(metric_name)
        if actual is None:
            continue
        try:
            actual_float = float(actual)
        except (TypeError, ValueError):
            continue
        metrics[metric_name] = _build_metric_spec(metric_name, actual_float)
    return metrics


def _build_meta(
    scenario: dict[str, Any],
    authoritative: bool,
    duration: int,
    author_commit: str | None,
    author_at: str | None,
) -> dict[str, Any]:
    """Build baseline metadata.

    Default metadata is explicitly non-authoritative. Authoritative metadata is
    only emitted when the commit is supplied; the timestamp defaults to now.
    """
    if authoritative:
        if not author_commit:
            raise ValueError(
                "Authoritative promotion requires PERF_BASELINE_AUTHORITATIVE_COMMIT"
            )
        validated_at = author_at or _authoritative_now()
        return {
            "authoritative": True,
            "last_validated_commit": author_commit,
            "validated_at": validated_at,
            "note": (
                "Authoritative baseline — validated on a controlled runner. "
                "Do not promote without a coverage gate and ADR update."
            ),
        }

    return {
        "authoritative": False,
        "last_validated_commit": "sample",
        "validated_at": "2026-01-01T00:00:00Z",
        "note": (
            "SAMPLE / NON-AUTHORITATIVE baseline for CI scaffolding. "
            "Generated by scripts/generate_perf_baselines.py. "
            "Do not use for blocking gates until validated on a controlled runner."
        ),
    }


def _build_baseline(
    scenario: dict[str, Any],
    authoritative: bool,
    duration: int,
    author_commit: str | None,
    author_at: str | None,
) -> dict[str, Any]:
    """Build a single baseline JSON document from a stress scenario result."""
    scenario_name = scenario.get("scenario", "unknown")
    concurrency = scenario.get("concurrency", 1)
    return {
        "format_version": "1.0",
        "scenario": scenario_name,
        "concurrency": concurrency,
        "duration_secs": duration,
        "metrics": _build_metrics(scenario),
        "meta": _build_meta(scenario, authoritative, duration, author_commit, author_at),
    }


def _authoritative_now() -> str:
    """Return an ISO 8601 UTC timestamp with Z suffix."""
    return datetime.datetime.now(tz=datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_stress_json(path: Path) -> dict[str, Any]:
    """Load ferrum-stress JSON output and validate top-level structure."""
    with path.open(encoding="utf-8") as fh:
        data = json.load(fh)

    if not isinstance(data, dict):
        raise ValueError("Stress JSON root must be an object")

    if "scenarios" not in data:
        raise ValueError("Stress JSON must contain a 'scenarios' array")

    return data


def generate_baselines(
    stress_data: dict[str, Any],
    output_dir: Path,
    duration: int,
    authoritative: bool,
    author_commit: str | None,
    author_at: str | None,
) -> list[Path]:
    """Generate baseline JSON files from stress output.

    Returns the list of written file paths.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    for scenario in stress_data.get("scenarios", []):
        if not isinstance(scenario, dict):
            print("[WARN] Skipping non-object scenario entry", file=sys.stderr)
            continue

        scenario_name = scenario.get("scenario", "unknown")
        if not scenario_name or scenario_name == "unknown":
            print("[WARN] Skipping scenario with missing name", file=sys.stderr)
            continue

        baseline = _build_baseline(scenario, authoritative, duration, author_commit, author_at)
        prefix = "baseline" if authoritative else "sample"
        filename = f"{prefix}_{_normalize_scenario_name(scenario_name)}_{duration}s.json"
        file_path = output_dir / filename

        with file_path.open("w", encoding="utf-8") as fh:
            json.dump(baseline, fh, indent=2)
            fh.write("\n")

        written.append(file_path)
        print(f"[OK] Wrote {file_path} (authoritative={authoritative})")

    return written


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate baseline JSON files from ferrum-stress output.",
    )
    parser.add_argument(
        "--stress-json",
        required=True,
        type=Path,
        help="Path to ferrum-stress JSON output file.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("baselines"),
        help="Directory to write baseline JSON files (default: baselines).",
    )
    parser.add_argument(
        "--duration",
        type=int,
        default=DEFAULT_DURATION_SECS,
        help="Scenario duration in seconds embedded in baseline metadata (default: 5).",
    )
    parser.add_argument(
        "--promote-authoritative",
        action="store_true",
        help=(
            "Emit authoritative metadata. Requires PERF_BASELINE_AUTHORITATIVE_COMMIT; "
            "PERF_BASELINE_AUTHORITATIVE_AT defaults to the current UTC time."
        ),
    )
    args = parser.parse_args()

    if not args.stress_json.is_file():
        print(f"[ERROR] Stress JSON file not found: {args.stress_json}", file=sys.stderr)
        return 1

    authoritative = args.promote_authoritative
    author_commit = os.environ.get("PERF_BASELINE_AUTHORITATIVE_COMMIT")
    author_at = os.environ.get("PERF_BASELINE_AUTHORITATIVE_AT") or (
        _authoritative_now() if authoritative else None
    )

    try:
        stress_data = load_stress_json(args.stress_json)
    except (json.JSONDecodeError, ValueError) as exc:
        print(f"[ERROR] Failed to load stress JSON: {exc}", file=sys.stderr)
        return 1

    try:
        written = generate_baselines(
            stress_data,
            args.output_dir,
            args.duration,
            authoritative,
            author_commit,
            author_at,
        )
    except ValueError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1

    if not written:
        print("[WARN] No baselines written.", file=sys.stderr)
        return 1

    print(f"[OK] Wrote {len(written)} baseline(s) to {args.output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
