#!/usr/bin/env python3
"""
D1–D6 Local Drill Runner for FerrumGate v1.

This script runs local evidence commands for compensation drill verification (D1–D6)
in an isolated test environment. It does NOT:
- Require a live ferrumd server (unless --server-url is provided for optional smoke)
- Complete any G2 gate or claim operator signoff
- Make a production-ready claim

Usage:
    # Run with defaults (output to /tmp/ferrum-drill-evidence/)
    python3 scripts/run_d1_d6_drills.py

    # Run with custom output directory
    python3 scripts/run_d1_d6_drills.py --output-dir /tmp/my-drill-evidence

    # Skip cargo tests (only generate skeleton from existing logs)
    python3 scripts/run_d1_d6_drills.py --skip-cargo

    # Run with optional server smoke (requires live server)
    python3 scripts/run_d1_d6_drills.py --server-url http://127.0.0.1:8080

    # JSON output only
    python3 scripts/run_d1_d6_drills.py --json-out

    # Markdown output only
    python3 scripts/run_d1_d6_drills.py --markdown-out

    # API-level drill plan (dry-run)
    python3 scripts/run_d1_d6_drills.py --api-drills --plan --server-url http://127.0.0.1:8080

    # API live lifecycle execution (attempts full governance chain)
    python3 scripts/run_d1_d6_drills.py --api-live --server-url http://127.0.0.1:8080 --bearer-token $FERRUM_BEARER_TOKEN

    # Run only selected drills
    python3 scripts/run_d1_d6_drills.py --api-live --server-url http://127.0.0.1:8080 --drills D1,D4

    # Help
    python3 scripts/run_d1_d6_drills.py --help

Evidence output is labeled "local/test-drill" and requires operator review.
Operator signoff per docs/implementation-path/59-pilot-readiness-evidence-packet.md.
"""

import argparse
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request
import uuid
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.resolve()
DEFAULT_OUTPUT_DIR = Path("/tmp/ferrum-drill-evidence")
SKELETON_GENERATOR = REPO_ROOT / "scripts" / "generate_evidence_skeleton.py"

DISCLAIMER = """
> **LOCAL/TEST-DRILL EVIDENCE — OPERATOR REVIEW REQUIRED**
>
> This evidence was generated by an automated local drill runner in a test environment.
> It does NOT complete any G2 gate, does NOT authorize a production pilot, and does NOT
> replace operator-executed drills in the target deployment environment.
>
> All evidence below requires operator review and explicit signoff per:
>   - D1-D6 drills: docs/implementation-path/58-workload-compensation-drill-evidence-template.md
>   - G2 gates: docs/implementation-path/59-pilot-readiness-evidence-packet.md
>
> **No production pilot signoff is implied or granted by this output.**
"""

DRILL_MAPPING = {
    "D1 (fs adapter)": {
        "crate": "ferrum-adapter-fs",
        "pattern": "test_rollback_",
        "description": "Filesystem adapter compensation/rollback tests",
        "cargo_args": ["-p", "ferrum-adapter-fs", "--", "test_rollback_"],
    },
    "D2 (git adapter)": {
        "crate": "ferrum-adapter-git",
        "pattern": "test_rollback_",
        "description": "Git adapter compensation/rollback tests",
        "cargo_args": ["-p", "ferrum-adapter-git", "--", "test_rollback_"],
    },
    "D3 (git remote fail-closed)": {
        "crate": "ferrum-adapter-git",
        "pattern": "test_git_push_rollback_returns_recovered_false_on_remote_deletion_failure",
        "description": "Git remote push fail-closed verification",
        "cargo_args": [
            "-p", "ferrum-adapter-git", "--",
            "test_git_push_rollback_returns_recovered_false_on_remote_deletion_failure",
        ],
    },
    "D4 (http adapter)": {
        "crate": "ferrum-adapter-http",
        "pattern": "test_compensate_|test_replay_",
        "description": "HTTP adapter compensation/replay tests",
        "cargo_args": ["-p", "ferrum-adapter-http", "--", "test_compensate_"],
    },
    "D5 (sqlite adapter)": {
        "crate": "ferrum-adapter-sqlite",
        "pattern": "rollback",
        "description": "SQLite adapter compensation/rollback tests",
        "cargo_args": ["-p", "ferrum-adapter-sqlite", "--", "rollback"],
    },
    "D6 (maildraft adapter)": {
        "crate": "ferrum-adapter-maildraft",
        "pattern": "rollback",
        "description": "Maildraft adapter compensation/rollback tests",
        "cargo_args": ["-p", "ferrum-adapter-maildraft", "--", "rollback"],
    },
}

DRILL_CARGO_TEST_MAPPING = {
    "D1 (fs adapter)": {
        "cargo_test": "ferrum-adapter-fs",
        "test_args": ["-p", "ferrum-adapter-fs", "--", "test_rollback_", "--test-threads=1"],
    },
    "D2 (git adapter)": {
        "cargo_test": "ferrum-adapter-git",
        "test_args": ["-p", "ferrum-adapter-git", "--", "test_rollback_", "--test-threads=1"],
    },
    "D3 (git remote fail-closed)": {
        "cargo_test": "ferrum-adapter-git",
        "test_args": [
            "-p", "ferrum-adapter-git", "--",
            "test_git_push_rollback_returns_recovered_false_on_remote_deletion_failure",
            "--test-threads=1",
        ],
    },
    "D4 (http adapter)": {
        "cargo_test": "ferrum-adapter-http",
        "test_args": ["-p", "ferrum-adapter-http", "--", "test_compensate_", "--test-threads=1"],
    },
    "D5 (sqlite adapter)": {
        "cargo_test": "ferrum-adapter-sqlite",
        "test_args": ["-p", "ferrum-adapter-sqlite", "--", "rollback", "--test-threads=1"],
    },
    "D6 (maildraft adapter)": {
        "cargo_test": "ferrum-adapter-maildraft",
        "test_args": ["-p", "ferrum-adapter-maildraft", "--", "rollback", "--test-threads=1"],
    },
}


def run_command(cmd, description, timeout=300, capture=True):
    """Run a command and return (success, output, returncode)."""
    print(f"\n{'=' * 60}")
    print(f"Running: {description}")
    print(f"Command: {' '.join(str(c) for c in cmd)}")
    print(f"{'=' * 60}")
    try:
        result = subprocess.run(
            cmd,
            shell=False,
            cwd=str(REPO_ROOT),
            capture_output=capture,
            text=True,
            timeout=timeout,
        )
        success = result.returncode == 0
        output = result.stdout + result.stderr if capture else ""
        return success, output, result.returncode
    except subprocess.TimeoutExpired:
        return False, f"Command timed out after {timeout}s", -1
    except Exception as e:
        return False, str(e), -1


def ensure_output_dir(output_dir):
    """Create output directory if it doesn't exist."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def run_cargo_tests(drill_name, cargo_args, output_dir):
    """Run cargo tests for a specific drill and capture output."""
    test_output_file = output_dir / f"{drill_name.replace(' ', '_').replace('(', '').replace(')', '')}_test_output.txt"
    combined_output = []

    cmd = ["cargo", "test", "--quiet"] + cargo_args

    success, output, rc = run_command(cmd, f"{drill_name} cargo tests", timeout=300)

    # Save raw output
    with open(test_output_file, "w", encoding="utf-8") as f:
        f.write(f"# {drill_name} Test Output\n")
        f.write(f"# Generated: {datetime.now(timezone.utc).isoformat()}\n")
        f.write(f"# Command: {' '.join(str(c) for c in cmd)}\n")
        f.write(f"# Return code: {rc}\n")
        f.write(f"# Success: {success}\n")
        f.write("\n## STDOUT/STDERR:\n\n")
        f.write(output)

    combined_output.append(output)

    test_count = parse_test_count(output)

    # Drill fails if cargo succeeded but found zero tests (pattern matched nothing)
    if success and test_count == 0:
        success = False

    return {
        "drill": drill_name,
        "success": success,
        "returncode": rc,
        "output_file": str(test_output_file),
        "test_count": test_count,
    }


def parse_test_count(output):
    """Parse test count from cargo test output."""
    import re
    match = re.search(r"(\d+) passed", output)
    if match:
        return int(match.group(1))
    match = re.search(r"(\d+) failed", output)
    if match:
        return -int(match.group(1))
    return 0


def run_server_smoke(server_url, bearer_token, output_dir):
    """Run optional server smoke checks if server URL is provided."""
    smoke_output_file = output_dir / "server_smoke_output.txt"
    combined = []

    # Import and run check_pilot_readiness
    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    try:
        from check_pilot_readiness import (
            check_shallow_readiness,
            check_deep_readiness,
            check_functional_readiness,
            check_metrics_endpoint,
        )

        results = {}
        for name, func in [
            ("shallow_readiness", check_shallow_readiness),
            ("deep_readiness", check_deep_readiness),
            ("functional_readiness", check_functional_readiness),
            ("metrics_endpoint", check_metrics_endpoint),
        ]:
            try:
                success, output = func(server_url, bearer_token)
                results[name] = {"success": success, "output": output[:500]}
            except Exception as e:
                results[name] = {"success": False, "output": str(e)}

        smoke_output = {
            "server_url": server_url,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "results": results,
        }

        with open(smoke_output_file, "w", encoding="utf-8") as f:
            f.write("# Server Smoke Output\n")
            f.write(f"# Generated: {datetime.now(timezone.utc).isoformat()}\n")
            f.write(f"# Server: {server_url}\n")
            f.write(json.dumps(smoke_output, indent=2))

        return {"success": True, "output_file": str(smoke_output_file), "results": results}

    except ImportError as e:
        return {"success": False, "output_file": str(smoke_output_file), "error": str(e)}


def generate_skeleton(content, output_dir, drill_type="d1-d6"):
    """Generate evidence skeleton using the existing generator script."""
    skeleton_output = output_dir / f"{drill_type}_evidence_skeleton.md"

    # Write content to temp file for skeleton generator
    temp_input = output_dir / f"{drill_type}_raw_input.txt"
    with open(temp_input, "w", encoding="utf-8") as f:
        f.write(content)

    cmd = [
        sys.executable,
        str(SKELETON_GENERATOR),
        "--type", drill_type,
        "--file", str(temp_input),
    ]

    success, output, rc = run_command(cmd, f"Generate {drill_type} evidence skeleton", timeout=30)

    if success:
        with open(skeleton_output, "w", encoding="utf-8") as f:
            f.write(output)
    else:
        # Fallback: write raw content with disclaimer
        with open(skeleton_output, "w", encoding="utf-8") as f:
            f.write(DISCLAIMER)
            f.write(f"\n\n# {drill_type.upper()} Evidence (Raw Output)\n\n")
            f.write(f"*Generated: {datetime.now(timezone.utc).isoformat()}*\n\n")
            f.write("```\n")
            f.write(content[:10000])  # Truncate if too long
            f.write("\n```\n")

    return str(skeleton_output)


def _redact_token(value):
    """Redact bearer token from a string for safe output."""
    if not value or len(value) < 8:
        return "<REDACTED>"
    return value[:4] + "..." + value[-4:]


def _make_api_request(method, url, headers, payload=None, timeout=30):
    """Make an API request using urllib and return (status, body_dict or str, error)."""
    data = None
    if payload is not None:
        data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, method=method, data=data, headers=headers, unverifiable=True)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read().decode("utf-8")
            try:
                return resp.status, json.loads(body), None
            except json.JSONDecodeError:
                return resp.status, body, None
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8") if e.fp else ""
        try:
            return e.code, json.loads(body), f"HTTP {e.code}: {e.reason}"
        except json.JSONDecodeError:
            return e.code, body, f"HTTP {e.code}: {e.reason}"
    except Exception as e:
        return None, None, str(e)


def probe_readyz_deep(server_url, bearer_token, output_dir, probe_count=5, probe_interval=10):
    """Probe /v1/readyz/deep repeatedly and record detailed results."""
    token = bearer_token or os.environ.get("FERRUM_BEARER_TOKEN", "")
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    url = f"{server_url}/v1/readyz/deep"
    results = []
    print(f"\nProbing {url} — {probe_count} probes at {probe_interval}s intervals")

    for i in range(probe_count):
        start = time.perf_counter()
        status, body, err = _make_api_request("GET", url, headers, timeout=30)
        elapsed_ms = round((time.perf_counter() - start) * 1000, 2)

        record = {
            "probe_number": i + 1,
            "timestamp": _now_rfc3339(),
            "url": url,
            "status_code": status,
            "latency_ms": elapsed_ms,
            "body_snippet": str(body)[:500] if body is not None else "",
            "error": err,
        }
        results.append(record)

        status_str = str(status) if status is not None else "TIMEOUT/ERROR"
        print(f"  Probe {i+1}/{probe_count}: HTTP {status_str} in {elapsed_ms}ms")
        if i < probe_count - 1:
            time.sleep(probe_interval)

    # Write JSON output
    json_file = output_dir / "readyz_deep_probe.json"
    with open(json_file, "w", encoding="utf-8") as f:
        json.dump(
            {
                "generated": _now_rfc3339(),
                "server_url": server_url,
                "probe_count": probe_count,
                "probe_interval_sec": probe_interval,
                "results": results,
            },
            f,
            indent=2,
        )

    # Write Markdown output
    md_file = output_dir / "readyz_deep_probe.md"
    with open(md_file, "w", encoding="utf-8") as f:
        f.write(DISCLAIMER)
        f.write("\n\n# /v1/readyz/deep Diagnostic Probe Log\n\n")
        f.write(f"*Generated: {_now_rfc3339()}*\n")
        f.write(f"*Server: {server_url}*\n")
        f.write(f"*Probes: {probe_count} at {probe_interval}s intervals*\n\n")
        f.write("## Results Summary\n\n")
        f.write("| Probe | Timestamp | Status | Latency (ms) | Body Snippet | Error |\n")
        f.write("|-------|-----------|--------|--------------|--------------|-------|\n")
        for r in results:
            err_cell = f"`{r['error']}`" if r["error"] else "—"
            body_cell = f"`{r['body_snippet'][:80]}`" if r["body_snippet"] else "—"
            f.write(
                f"| {r['probe_number']} | {r['timestamp']} | {r['status_code']} "
                f"| {r['latency_ms']} | {body_cell} | {err_cell} |\n"
            )
        f.write("\n## Detailed Records\n\n")
        for r in results:
            f.write(f"### Probe {r['probe_number']} — {r['timestamp']}\n\n")
            f.write(f"- **Status Code**: {r['status_code']}\n")
            f.write(f"- **Latency**: {r['latency_ms']} ms\n")
            f.write(f"- **Body Snippet**: `{r['body_snippet']}`\n")
            if r["error"]:
                f.write(f"- **Error**: `{r['error']}`\n")
            f.write("\n")
        f.write("\n---\n*Generated by run_d1_d6_drills.py — operator review required.*\n")

    return str(json_file), str(md_file), results


def _normalize_intent_compile_payload(payload):
    """Return a copy of the intent compile payload with required defaults applied."""
    normalized = dict(payload)
    if "trusted_context" not in normalized:
        normalized["trusted_context"] = {}
    return normalized


API_DRILL_TEMPLATES = {
    "D1 (fs adapter)": {
        "intent_compile_payload": {
            "principal_id": "00000000-0000-0000-0000-000000000001",
            "title": "D1 FS Drill",
            "goal": "Write file /tmp/ferrum_d1_drill.txt for rollback verification",
            "raw_inputs": [],
            "requested_resource_scope": [
                {
                    "kind": "FilesystemPath",
                    "path": "/tmp/ferrum_d1_drill.txt",
                    "mode": "Write",
                    "content_hash": None,
                }
            ],
            "metadata": {"drill": "D1", "adapter": "fs"},
        },
        "proposal": {
            "step_index": 0,
            "title": "D1 FS Write",
            "tool_name": "fs_write",
            "server_name": "local",
            "raw_arguments": {"path": "/tmp/ferrum_d1_drill.txt"},
            "expected_effect": "FileMutation",
            "estimated_risk": "Low",
            "requested_rollback_class": "R2Compensatable",
            "taint_inputs": [],
            "metadata": {},
        },
        "capability": {
            "tool_binding": {"server_name": "local", "tool_name": "fs_write", "tool_version": None},
            "resource_bindings": [
                {"kind": "File", "path": "/tmp/ferrum_d1_drill.txt", "mode": "Write", "required_hash": None}
            ],
            "argument_constraints": [],
            "taint_budget": {
                "max_taint_score": 0,
                "allow_external_tool_output": False,
                "allow_external_metadata": False,
                "allow_untrusted_text": False,
            },
            "approval_binding": None,
            "requested_ttl_secs": 300,
            "metadata": {},
        },
        "execute_payload": {"content": "D1 drill content from lifecycle runner"},
        "adapter_notes": "FileWrite adapter uses payload.content as file content.",
    },
    "D2 (git adapter)": {
        "intent_compile_payload": {
            "principal_id": "00000000-0000-0000-0000-000000000001",
            "title": "D2 Git Drill",
            "goal": "Git branch create in /tmp/ferrum_d2_repo for rollback verification",
            "raw_inputs": [],
            "requested_resource_scope": [
                {
                    "kind": "GitRepository",
                    "repo_path": "/tmp/ferrum_d2_repo",
                    "allowed_refs": ["main"],
                    "mode": "Write",
                }
            ],
            "metadata": {"drill": "D2", "adapter": "git"},
        },
        "proposal": {
            "step_index": 0,
            "title": "D2 Git Branch Create",
            "tool_name": "git_branch_create",
            "server_name": "local",
            "raw_arguments": {"branch": "d2-drill-branch"},
            "expected_effect": "GitMutation",
            "estimated_risk": "Low",
            "requested_rollback_class": "R2Compensatable",
            "taint_inputs": [],
            "metadata": {},
        },
        "capability": {
            "tool_binding": {"server_name": "local", "tool_name": "git_branch_create", "tool_version": None},
            "resource_bindings": [
                {"kind": "Git", "repo_path": "/tmp/ferrum_d2_repo", "allowed_refs": ["main"], "mode": "Write"}
            ],
            "argument_constraints": [],
            "taint_budget": {
                "max_taint_score": 0,
                "allow_external_tool_output": False,
                "allow_external_metadata": False,
                "allow_untrusted_text": False,
            },
            "approval_binding": None,
            "requested_ttl_secs": 300,
            "metadata": {},
        },
        "execute_payload": {},
        "adapter_notes": "Git adapter execute payload is typically empty; operation is encoded in the contract target.",
    },
    "D3 (git remote fail-closed)": {
        "intent_compile_payload": {
            "principal_id": "00000000-0000-0000-0000-000000000001",
            "title": "D3 Git Remote Drill",
            "goal": "Git push to non-prod remote with fail-closed verification",
            "raw_inputs": [],
            "requested_resource_scope": [
                {
                    "kind": "GitRepository",
                    "repo_path": "/tmp/ferrum_d3_repo",
                    "allowed_refs": ["main"],
                    "mode": "Write",
                }
            ],
            "metadata": {"drill": "D3", "adapter": "git", "remote": "origin"},
        },
        "proposal": {
            "step_index": 0,
            "title": "D3 Git Push",
            "tool_name": "git_push",
            "server_name": "local",
            "raw_arguments": {"remote": "origin", "refspec": "main"},
            "expected_effect": "GitMutation",
            "estimated_risk": "High",
            "requested_rollback_class": "R2Compensatable",
            "taint_inputs": [],
            "metadata": {},
        },
        "capability": {
            "tool_binding": {"server_name": "local", "tool_name": "git_push", "tool_version": None},
            "resource_bindings": [
                {"kind": "Git", "repo_path": "/tmp/ferrum_d3_repo", "allowed_refs": ["main"], "mode": "Write"}
            ],
            "argument_constraints": [],
            "taint_budget": {
                "max_taint_score": 0,
                "allow_external_tool_output": False,
                "allow_external_metadata": False,
                "allow_untrusted_text": False,
            },
            "approval_binding": None,
            "requested_ttl_secs": 300,
            "metadata": {},
        },
        "execute_payload": {},
        "adapter_notes": "Requires non-prod bare remote. Fail-closed verified via pre-receive hook.",
    },
    "D4 (http adapter)": {
        "intent_compile_payload": {
            "principal_id": "00000000-0000-0000-0000-000000000001",
            "title": "D4 HTTP Drill",
            "goal": "HTTP POST to test endpoint with idempotency-aware compensation",
            "raw_inputs": [],
            "requested_resource_scope": [
                {
                    "kind": "HttpEndpoint",
                    "method": "Post",
                    "base_url": "https://httpbin.org",
                    "path_prefix": "/post",
                    "mode": "Write",
                }
            ],
            "metadata": {"drill": "D4", "adapter": "http"},
        },
        "proposal": {
            "step_index": 0,
            "title": "D4 HTTP POST",
            "tool_name": "http_post",
            "server_name": "local",
            "raw_arguments": {"url": "https://httpbin.org/post", "body": "{\"drill\": \"D4\"}"},
            "expected_effect": "ExternalApiCall",
            "estimated_risk": "Medium",
            "requested_rollback_class": "R2Compensatable",
            "taint_inputs": [],
            "metadata": {},
        },
        "capability": {
            "tool_binding": {"server_name": "local", "tool_name": "http_post", "tool_version": None},
            "resource_bindings": [
                {
                    "kind": "Http",
                    "method": "Post",
                    "base_url": "https://httpbin.org",
                    "path_prefix": "/post",
                    "header_allowlist": ["Content-Type"],
                    "mode": "Write",
                }
            ],
            "argument_constraints": [],
            "taint_budget": {
                "max_taint_score": 0,
                "allow_external_tool_output": False,
                "allow_external_metadata": False,
                "allow_untrusted_text": False,
            },
            "approval_binding": None,
            "requested_ttl_secs": 300,
            "metadata": {},
        },
        "execute_payload": {"body": '{"drill": "D4 HTTP POST"}'},
        "adapter_notes": (
            "HTTP adapter supports POST/PUT/PATCH with idempotency key. "
            "Compensation plan must use http.replay_v1 operation. "
            "NOTE: server infer_action_type_and_adapter may default HTTP tools to noop adapter; "
            "live execution may fail unless HTTP adapter is fully wired in target build."
        ),
    },
    "D5 (sqlite adapter)": {
        "intent_compile_payload": {
            "principal_id": "00000000-0000-0000-0000-000000000001",
            "title": "D5 SQLite Drill",
            "goal": "SQLite DML insert with transaction rollback verification",
            "raw_inputs": [],
            "requested_resource_scope": [
                {
                    "kind": "SqliteDatabase",
                    "db_path": "/tmp/ferrum_d5.db",
                    "tables": ["drill_table"],
                    "mode": "Write",
                }
            ],
            "metadata": {"drill": "D5", "adapter": "sqlite"},
        },
        "proposal": {
            "step_index": 0,
            "title": "D5 SQLite Mutation",
            "tool_name": "sql_mutate",
            "server_name": "local",
            "raw_arguments": {"sql": "INSERT INTO drill_table (id, value) VALUES (1, 'D5 drill')"},
            "expected_effect": "DatabaseMutation",
            "estimated_risk": "Medium",
            "requested_rollback_class": "R2Compensatable",
            "taint_inputs": [],
            "metadata": {},
        },
        "capability": {
            "tool_binding": {"server_name": "local", "tool_name": "sql_mutate", "tool_version": None},
            "resource_bindings": [
                {"kind": "Sqlite", "db_path": "/tmp/ferrum_d5.db", "tables": ["drill_table"], "mode": "Write"}
            ],
            "argument_constraints": [],
            "taint_budget": {
                "max_taint_score": 0,
                "allow_external_tool_output": False,
                "allow_external_metadata": False,
                "allow_untrusted_text": False,
            },
            "approval_binding": None,
            "requested_ttl_secs": 300,
            "metadata": {},
        },
        "execute_payload": {"sql": "INSERT INTO drill_table (id, value) VALUES (1, 'D5 drill')"},
        "adapter_notes": "SQLite adapter accepts payload with 'sql' field. DML uses SAVEPOINT; DDL uses schema capture.",
    },
    "D6 (maildraft adapter)": {
        "intent_compile_payload": {
            "principal_id": "00000000-0000-0000-0000-000000000001",
            "title": "D6 MailDraft Drill",
            "goal": "Create email draft with rollback verification",
            "raw_inputs": [],
            "requested_resource_scope": [
                {
                    "kind": "EmailDraft",
                    "recipient_allowlist": ["drill@example.com"],
                    "subject_prefix_allowlist": ["D6"],
                    "mode": "Write",
                }
            ],
            "metadata": {"drill": "D6", "adapter": "maildraft"},
        },
        "proposal": {
            "step_index": 0,
            "title": "D6 MailDraft Create",
            "tool_name": "maildraft_create",
            "server_name": "local",
            "raw_arguments": {
                "draft_id": "d6-drill-1",
                "from": "drill@example.com",
                "to": ["recipient@example.com"],
                "subject": "D6 drill",
                "body": "D6 maildraft compensation drill",
            },
            "expected_effect": "ExternalCommunication",
            "estimated_risk": "Low",
            "requested_rollback_class": "R2Compensatable",
            "taint_inputs": [],
            "metadata": {},
        },
        "capability": {
            "tool_binding": {"server_name": "local", "tool_name": "maildraft_create", "tool_version": None},
            "resource_bindings": [
                {"kind": "EmailDraft", "recipients": ["recipient@example.com"], "allow_send": False, "mode": "Write"}
            ],
            "argument_constraints": [],
            "taint_budget": {
                "max_taint_score": 0,
                "allow_external_tool_output": False,
                "allow_external_metadata": False,
                "allow_untrusted_text": False,
            },
            "approval_binding": None,
            "requested_ttl_secs": 300,
            "metadata": {},
        },
        "execute_payload": {
            "draft_id": "d6-drill-1",
            "from": "drill@example.com",
            "to": ["recipient@example.com"],
            "subject": "D6 drill",
            "body": "D6 maildraft compensation drill",
        },
        "adapter_notes": "MailDraft adapter accepts draft fields in execute payload. Supports create, update, delete operations.",
    },
}


def _now_rfc3339():
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _curl_block(method, url, headers, payload, placeholder_token):
    """Generate a markdown curl code block using heredoc for shell-safe payloads."""
    lines = ["```bash"]
    cmd_parts = [f"curl -s -X {method} '{url}'"]
    if placeholder_token:
        cmd_parts.append("  -H 'Authorization: Bearer $FERRUM_BEARER_TOKEN'")
    for k, v in headers.items():
        if k.lower() == "authorization":
            continue
        cmd_parts.append(f"  -H '{k}: {v}'")
    if payload is not None:
        payload_json = json.dumps(payload, indent=2)
        cmd_parts.append("  -d @- <<'PAYLOAD'")
        curl_cmd = " \\\n".join(cmd_parts)
        lines.append(curl_cmd)
        lines.append(payload_json)
        lines.append("PAYLOAD")
    else:
        curl_cmd = " \\\n".join(cmd_parts)
        lines.append(curl_cmd)
    lines.append("```")
    return lines


def run_api_drills(server_url, bearer_token, plan_mode, output_dir, rate_limit_delay, selected_drills=None):
    """Run or plan API-level D1-D6 drills against a live FerrumGate server."""
    token = bearer_token or os.environ.get("FERRUM_BEARER_TOKEN", "")
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    # Determine which drills to run
    drills_to_run = {}
    for drill_name, template in API_DRILL_TEMPLATES.items():
        key = drill_name.split()[0]  # e.g., "D1"
        if selected_drills is None or key in selected_drills:
            drills_to_run[drill_name] = template

    results = {}
    api_output_lines = []
    api_output_lines.append("# D1-D6 API Drill Commands")
    api_output_lines.append(f"*Generated: {_now_rfc3339()}*")
    api_output_lines.append(f"*Server: {server_url}*")
    api_output_lines.append(f"*Mode: {'PLAN (dry-run)' if plan_mode else 'LIVE'}*")
    api_output_lines.append("")
    api_output_lines.append("> **LIMITATION**: Full automated API drill execution requires the complete")
    api_output_lines.append("> intent-compile → proposal-evaluate → capability-mint → execution-authorize")
    api_output_lines.append("> lifecycle chain. Some steps may fail if the target server build does not")
    api_output_lines.append("> wire the requested adapter (e.g., HTTP adapter defaults to noop).")
    api_output_lines.append("")

    for drill_name, template in drills_to_run.items():
        api_output_lines.append(f"## {drill_name}")
        api_output_lines.append("")
        api_output_lines.append(f"**Adapter notes**: {template['adapter_notes']}")
        api_output_lines.append("")

        drill_result = {
            "drill": drill_name,
            "steps": {},
            "overall_status": "planned" if plan_mode else "pending",
        }

        # Step 1: Compile Intent
        step_name = "1_compile_intent"
        api_output_lines.append("### 1. Compile Intent")
        compile_url = f"{server_url}/v1/intents/compile"
        compile_payload = _normalize_intent_compile_payload(template["intent_compile_payload"])
        api_output_lines.extend(_curl_block("POST", compile_url, {"Content-Type": "application/json"}, compile_payload, token))
        api_output_lines.append("")

        intent_id = None
        if not plan_mode:
            time.sleep(rate_limit_delay)
            status, body, err = _make_api_request("POST", compile_url, headers, compile_payload)
            if status in (200, 201) and isinstance(body, dict) and "envelope" in body:
                intent_id = body["envelope"].get("intent_id")
                if intent_id:
                    drill_result["steps"][step_name] = {"status": "passed", "intent_id": intent_id}
                else:
                    drill_result["steps"][step_name] = {
                        "status": "failed",
                        "http_status": status,
                        "error": "Missing intent_id in compile response envelope",
                        "body": body,
                    }
                    drill_result["overall_status"] = "failed"
            else:
                drill_result["steps"][step_name] = {
                    "status": "failed",
                    "http_status": status,
                    "error": err,
                    "body": body,
                }
                drill_result["overall_status"] = "failed"
        else:
            drill_result["steps"][step_name] = {"status": "planned"}

        # Step 2: Evaluate ActionProposal
        step_name = "2_evaluate_proposal"
        api_output_lines.append("### 2. Evaluate ActionProposal")
        proposal_id = str(uuid.uuid4())
        proposal_payload = dict(template["proposal"])
        proposal_payload["proposal_id"] = proposal_id
        proposal_payload["intent_id"] = intent_id or "<INTENT_ID_FROM_STEP_1>"
        proposal_payload["created_at"] = _now_rfc3339()
        evaluate_url = f"{server_url}/v1/proposals/{proposal_id}/evaluate"
        api_output_lines.extend(_curl_block("POST", evaluate_url, {"Content-Type": "application/json"}, proposal_payload, token))
        api_output_lines.append("")

        decision = None
        if not plan_mode and intent_id and drill_result["overall_status"] != "failed":
            time.sleep(rate_limit_delay)
            status, body, err = _make_api_request("POST", evaluate_url, headers, proposal_payload)
            if status == 200 and isinstance(body, dict):
                decision = body.get("decision")
                drill_result["steps"][step_name] = {"status": "passed", "decision": decision}
                if decision not in ("Allow",):
                    drill_result["overall_status"] = "failed"
            else:
                drill_result["steps"][step_name] = {
                    "status": "failed",
                    "http_status": status,
                    "error": err,
                    "body": body,
                }
                drill_result["overall_status"] = "failed"
        elif plan_mode:
            drill_result["steps"][step_name] = {"status": "planned"}
        else:
            drill_result["steps"][step_name] = {"status": "skipped", "reason": "previous step failed"}

        # Step 3: Mint Capability
        step_name = "3_mint_capability"
        api_output_lines.append("### 3. Mint Capability")
        capability_payload = dict(template["capability"])
        capability_payload["intent_id"] = intent_id or "<INTENT_ID_FROM_STEP_1>"
        capability_payload["proposal_id"] = proposal_id
        mint_url = f"{server_url}/v1/capabilities/mint"
        api_output_lines.extend(_curl_block("POST", mint_url, {"Content-Type": "application/json"}, capability_payload, token))
        api_output_lines.append("")

        capability_id = None
        if not plan_mode and intent_id and drill_result["overall_status"] != "failed":
            time.sleep(rate_limit_delay)
            status, body, err = _make_api_request("POST", mint_url, headers, capability_payload)
            if status in (200, 201) and isinstance(body, dict) and "lease" in body:
                capability_id = body["lease"].get("capability_id")
                if capability_id:
                    drill_result["steps"][step_name] = {"status": "passed", "capability_id": capability_id}
                else:
                    drill_result["steps"][step_name] = {
                        "status": "failed",
                        "http_status": status,
                        "error": "Missing capability_id in mint response lease",
                        "body": body,
                    }
                    drill_result["overall_status"] = "failed"
            else:
                drill_result["steps"][step_name] = {
                    "status": "failed",
                    "http_status": status,
                    "error": err,
                    "body": body,
                }
                drill_result["overall_status"] = "failed"
        elif plan_mode:
            drill_result["steps"][step_name] = {"status": "planned"}
        else:
            drill_result["steps"][step_name] = {"status": "skipped", "reason": "previous step failed"}

        # Step 4: Authorize Execution
        step_name = "4_authorize_execution"
        api_output_lines.append("### 4. Authorize Execution")
        authorize_payload = {
            "proposal_id": proposal_id,
            "capability_id": capability_id or "<CAPABILITY_ID_FROM_STEP_3>",
            "dry_run": False,
        }
        authorize_url = f"{server_url}/v1/executions/authorize"
        api_output_lines.extend(_curl_block("POST", authorize_url, {"Content-Type": "application/json"}, authorize_payload, token))
        api_output_lines.append("")

        execution_id = None
        if not plan_mode and capability_id and drill_result["overall_status"] != "failed":
            time.sleep(rate_limit_delay)
            status, body, err = _make_api_request("POST", authorize_url, headers, authorize_payload)
            if status == 200 and isinstance(body, dict) and "execution" in body:
                execution_id = body["execution"].get("execution_id")
                drill_result["steps"][step_name] = {"status": "passed", "execution_id": execution_id}
            else:
                drill_result["steps"][step_name] = {
                    "status": "failed",
                    "http_status": status,
                    "error": err,
                    "body": body,
                }
                drill_result["overall_status"] = "failed"
        elif plan_mode:
            drill_result["steps"][step_name] = {"status": "planned"}
        else:
            drill_result["steps"][step_name] = {"status": "skipped", "reason": "previous step failed"}

        # Step 5: Prepare Execution
        step_name = "5_prepare_execution"
        api_output_lines.append("### 5. Prepare Execution")
        prepare_url = f"{server_url}/v1/executions/{execution_id or '<EXECUTION_ID_FROM_STEP_4>'}/prepare"
        api_output_lines.extend(_curl_block("POST", prepare_url, {"Content-Type": "application/json"}, None, token))
        api_output_lines.append("")

        prepared = False
        if not plan_mode and execution_id and drill_result["overall_status"] != "failed":
            time.sleep(rate_limit_delay)
            status, body, err = _make_api_request("POST", prepare_url, headers)
            if status == 200 and isinstance(body, dict):
                prepared = body.get("prepared", False)
                drill_result["steps"][step_name] = {"status": "passed" if prepared else "failed", "prepared": prepared}
                if not prepared:
                    drill_result["overall_status"] = "failed"
            else:
                drill_result["steps"][step_name] = {
                    "status": "failed",
                    "http_status": status,
                    "error": err,
                    "body": body,
                }
                drill_result["overall_status"] = "failed"
        elif plan_mode:
            drill_result["steps"][step_name] = {"status": "planned"}
        else:
            drill_result["steps"][step_name] = {"status": "skipped", "reason": "previous step failed"}

        # Step 6: Execute Adapter Operation
        step_name = "6_execute"
        api_output_lines.append("### 6. Execute Adapter Operation")
        execute_url = f"{server_url}/v1/executions/{execution_id or '<EXECUTION_ID_FROM_STEP_4>'}/execute"
        execute_payload = {"payload": template["execute_payload"]}
        api_output_lines.extend(_curl_block("POST", execute_url, {"Content-Type": "application/json"}, execute_payload, token))
        api_output_lines.append("")

        executed = False
        if not plan_mode and execution_id and drill_result["overall_status"] != "failed":
            time.sleep(rate_limit_delay)
            status, body, err = _make_api_request("POST", execute_url, headers, execute_payload)
            if status == 200 and isinstance(body, dict):
                executed = body.get("executed", False)
                drill_result["steps"][step_name] = {
                    "status": "passed" if executed else "failed",
                    "executed": executed,
                    "result_digest": body.get("result_digest"),
                }
                if not executed:
                    drill_result["overall_status"] = "failed"
            else:
                drill_result["steps"][step_name] = {
                    "status": "failed",
                    "http_status": status,
                    "error": err,
                    "body": body,
                }
                drill_result["overall_status"] = "failed"
        elif plan_mode:
            drill_result["steps"][step_name] = {"status": "planned"}
        else:
            drill_result["steps"][step_name] = {"status": "skipped", "reason": "previous step failed"}

        # Step 7: Compensate Execution
        step_name = "7_compensate"
        api_output_lines.append("### 7. Compensate Execution")
        compensate_url = f"{server_url}/v1/executions/{execution_id or '<EXECUTION_ID_FROM_STEP_4>'}/compensate"
        api_output_lines.extend(_curl_block("POST", compensate_url, {"Content-Type": "application/json"}, None, token))
        api_output_lines.append("")

        compensated = False
        if not plan_mode and execution_id and drill_result["overall_status"] != "failed":
            time.sleep(rate_limit_delay)
            status, body, err = _make_api_request("POST", compensate_url, headers)
            if status == 200 and isinstance(body, dict):
                compensated = body.get("compensated", False)
                drill_result["steps"][step_name] = {"status": "passed" if compensated else "failed", "compensated": compensated}
                # Compensation failure does not necessarily fail the overall drill
                # because some adapters may not support compensation for all operations.
                if not compensated:
                    drill_result["overall_status"] = "partial"
            else:
                drill_result["steps"][step_name] = {
                    "status": "failed",
                    "http_status": status,
                    "error": err,
                    "body": body,
                }
                drill_result["overall_status"] = "partial"
        elif plan_mode:
            drill_result["steps"][step_name] = {"status": "planned"}
        else:
            drill_result["steps"][step_name] = {"status": "skipped", "reason": "previous step failed"}

        # Step 8: Verify Execution Outcome
        # For compensation drills, verify is not applicable after compensate.
        # The gateway contract requires compensate while the contract is in ExecutedAwaitingVerify;
        # calling verify first would transition to Verified and block compensation.
        step_name = "8_verify"
        api_output_lines.append("### 8. Verify Execution Outcome")
        verify_url = f"{server_url}/v1/executions/{execution_id or '<EXECUTION_ID_FROM_STEP_4>'}/verify"
        api_output_lines.extend(_curl_block("POST", verify_url, {"Content-Type": "application/json"}, None, token))
        api_output_lines.append("")

        if plan_mode:
            drill_result["steps"][step_name] = {
                "status": "planned",
                "note": "Skipped for compensation drills — verify endpoint is for commit-path flows. Compensation drills call compensate immediately after execute while contract is in ExecutedAwaitingVerify.",
            }
        elif execution_id and drill_result["overall_status"] != "failed":
            # Skip live verify for compensation drills to avoid state conflict.
            drill_result["steps"][step_name] = {
                "status": "skipped",
                "reason": "Not applicable for compensation drill — verify transitions contract away from ExecutedAwaitingVerify and would block compensation. Compensation drills rely on post-compensate state checks.",
            }
        else:
            drill_result["steps"][step_name] = {"status": "skipped", "reason": "previous step failed"}

        # Step 9: Capture Evidence (query execution record)
        step_name = "9_capture_evidence"
        api_output_lines.append("### 9. Capture Evidence")
        get_url = f"{server_url}/v1/executions/{execution_id or '<EXECUTION_ID_FROM_STEP_4>'}"
        api_output_lines.extend(_curl_block("GET", get_url, {"Content-Type": "application/json"}, None, token))
        api_output_lines.append("")

        if not plan_mode and execution_id:
            time.sleep(rate_limit_delay)
            status, body, err = _make_api_request("GET", get_url, headers)
            if status == 200 and isinstance(body, dict):
                drill_result["steps"][step_name] = {"status": "passed", "execution_record": body}
            else:
                drill_result["steps"][step_name] = {
                    "status": "failed",
                    "http_status": status,
                    "error": err,
                    "body": body,
                }
        elif plan_mode:
            drill_result["steps"][step_name] = {"status": "planned"}
        else:
            drill_result["steps"][step_name] = {"status": "skipped", "reason": "no execution_id"}

        if plan_mode:
            drill_result["overall_status"] = "planned"
        elif drill_result["overall_status"] == "pending":
            drill_result["overall_status"] = "passed"

        results[drill_name] = drill_result

    # Write API drill output
    api_output_file = output_dir / "api_drill_commands.md"
    with open(api_output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(api_output_lines))

    return results, str(api_output_file)


def generate_markdown_summary(results, output_dir, server_smoke=None, plan_mode=False, evidence_label=""):
    """Generate markdown summary of drill results."""
    md_file = output_dir / "drill_summary.md"

    with open(md_file, "w", encoding="utf-8") as f:
        f.write(DISCLAIMER)
        f.write("\n\n")
        f.write("# D1–D6 Drill Runner Summary\n\n")
        f.write(f"*Generated: {datetime.now(timezone.utc).isoformat()}*\n")
        f.write(f"*Repository: {REPO_ROOT}*\n")
        f.write(f"*Output directory: {output_dir}*\n")
        if evidence_label:
            f.write(f"*Evidence label: {evidence_label}*\n")
        f.write("\n")

        f.write("---\n\n")
        f.write("## Run Context\n\n")
        f.write("| Field | Value |\n")
        f.write("|-------|-------|\n")
        f.write(f"| Environment | Local/test-drill only |\n")
        f.write(f"| Generated | {datetime.now(timezone.utc).isoformat()} |\n")
        f.write(f"| Evidence dir | {output_dir} |\n")
        if evidence_label:
            f.write(f"| Evidence label | {evidence_label} |\n")
        f.write("| Server smoke | ")
        if plan_mode:
            f.write("Skipped in plan mode\n")
        elif server_smoke:
            f.write(f"PASS ({server_smoke.get('server_url', 'N/A')})\n")
        else:
            f.write("Not run (no --server-url provided)\n")
        f.write("\n---\n\n")

        if plan_mode:
            f.write("## Planned API Drills\n\n")
            f.write("| Drill | Status | Notes |\n")
            f.write("|-------|--------|-------|\n")
            for drill_name, result in results.items():
                f.write(f"| {drill_name} | Planned | API lifecycle generated, not executed |\n")
            f.write("\n---\n\n")
            f.write("> **Note**: Plan mode generated all 9 lifecycle steps as curl commands. ")
            f.write("Step 8 (verify) is noted as skipped for compensation drills because verify transitions the contract away from ExecutedAwaitingVerify and would block compensation. ")
            f.write("No live requests were sent. Operator must review and adapt payloads before execution.\n")
        else:
            f.write("## Drill Results\n\n")
            f.write("| Drill | Overall | Steps |\n")
            f.write("|-------|---------|-------|\n")

            for drill_name, result in results.items():
                overall = result.get("overall_status", "unknown")
                if overall == "passed":
                    status_emoji = "[PASS]"
                elif overall == "partial":
                    status_emoji = "[PARTIAL]"
                else:
                    status_emoji = "[FAIL]"
                steps_summary = ", ".join(
                    f"{k.split('_', 1)[1]}={v['status']}" for k, v in result.get("steps", {}).items()
                )
                f.write(f"| {status_emoji} {drill_name} | {overall} | {steps_summary} |\n")

        f.write("\n---\n\n")

        f.write("## Step Details\n\n")
        for drill_name, result in results.items():
            f.write(f"### {drill_name}\n\n")
            for step_key, step in result.get("steps", {}).items():
                step_label = step_key.split("_", 1)[1].replace("_", " ").title()
                status = step.get("status", "unknown")
                if status == "passed":
                    emoji = "[OK]"
                elif status == "failed":
                    emoji = "[FAIL]"
                elif status == "skipped":
                    emoji = "[SKIP]"
                else:
                    emoji = "[PLAN]"
                f.write(f"- {emoji} **{step_label}**: {status}")
                if "error" in step:
                    err_str = str(step["error"])[:200]
                    f.write(f" — Error: `{err_str}`")
                if "http_status" in step:
                    f.write(f" (HTTP {step['http_status']})")
                if "note" in step:
                    note_str = str(step["note"])[:200]
                    f.write(f" — Note: {note_str}")
                if "reason" in step:
                    reason_str = str(step["reason"])[:200]
                    f.write(f" — Reason: {reason_str}")
                f.write("\n")
            f.write("\n")

        f.write("---\n\n")

        f.write("## Limitations / Operator Follow-Up\n\n")
        f.write("- D1–D6 evidence is adapter-level test evidence, not full end-to-end operator drills.\n")
        f.write("- D3 confirms fail-closed behavior at adapter level; operator must evaluate target remote branch protection.\n")
        f.write("- D4 did not exercise a live external HTTP service (HTTP adapter may default to noop).\n")
        f.write("- D5 requires a real SQLite database and table schema on the target host.\n")
        f.write("- D6 requires a real maildraft backend or mock.\n")
        f.write("- Signature fields remain blank until operator reviews evidence and signs per docs 58/59.\n")
        f.write("- No production pilot signoff is implied or granted.\n")
        f.write("- Compensation (step 7) may fail for adapters where rollback is not yet fully wired.\n")

        f.write("\n---\n\n")
        f.write("*Generated by run_d1_d6_drills.py — operator review required before use.*\n")

    return str(md_file)


def generate_json_summary(results, output_dir, server_smoke=None, plan_mode=False, evidence_label=""):
    """Generate JSON summary of drill results."""
    json_file = output_dir / "drill_summary.json"

    summary = {
        "generated": datetime.now(timezone.utc).isoformat(),
        "repository": str(REPO_ROOT),
        "output_dir": str(output_dir),
        "disclaimer": "LOCAL/TEST-DRILL EVIDENCE — OPERATOR REVIEW REQUIRED",
        "evidence_label": evidence_label,
        "run_context": {
            "environment": "local/test-drill only",
            "plan_mode": plan_mode,
            "server_smoke": server_smoke.get("server_url") if server_smoke else None,
            "server_smoke_passed": server_smoke.get("success") if server_smoke else None,
        },
        "drill_results": {},
        "evidence_files": [],
    }

    for drill_name, result in results.items():
        steps = {}
        for k, v in result.get("steps", {}).items():
            steps[k] = {key: val for key, val in v.items() if key not in ("execution_record",)}
        summary["drill_results"][drill_name] = {
            "overall_status": result.get("overall_status", "unknown"),
            "steps": steps,
        }

    with open(json_file, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    return str(json_file)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Run D1–D6 local evidence drills for FerrumGate v1.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run all drills with defaults
  python3 scripts/run_d1_d6_drills.py

  # Skip cargo tests, only generate skeleton from existing logs
  python3 scripts/run_d1_d6_drills.py --skip-cargo

  # Run with optional server smoke
  python3 scripts/run_d1_d6_drills.py --server-url http://127.0.0.1:8080

  # Custom output directory
  python3 scripts/run_d1_d6_drills.py --output-dir /tmp/my-drill-evidence

  # JSON output only
  python3 scripts/run_d1_d6_drills.py --json-out --skip-cargo

  # API-level drill plan (dry-run)
  python3 scripts/run_d1_d6_drills.py --api-drills --plan --server-url http://127.0.0.1:8080

  # API live lifecycle execution (attempts full governance chain)
  python3 scripts/run_d1_d6_drills.py --api-live --server-url http://127.0.0.1:8080 --bearer-token $FERRUM_BEARER_TOKEN

  # Run only selected drills in live mode
  python3 scripts/run_d1_d6_drills.py --api-live --server-url http://127.0.0.1:8080 --drills D1,D4

  # Diagnostic readyz/deep probe (plan mode)
  python3 scripts/run_d1_d6_drills.py --probe-readyz-deep --plan --server-url http://127.0.0.1:8080

  # Diagnostic readyz/deep probe (live)
  python3 scripts/run_d1_d6_drills.py --probe-readyz-deep --server-url http://127.0.0.1:8080 --bearer-token $FERRUM_BEARER_TOKEN

IMPORTANT:
  This script does NOT complete G2/operator signoff.
  Operator review and explicit signoff is still required.
  See: docs/implementation-path/59-pilot-readiness-evidence-packet.md
        """,
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory for evidence (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--skip-cargo",
        action="store_true",
        help="Skip cargo test execution (use with --server-url for smoke only)",
    )
    parser.add_argument(
        "--server-url",
        type=str,
        default=None,
        help="Optional: FerrumGate server URL for readiness smoke or API drills",
    )
    parser.add_argument(
        "--json-out",
        action="store_true",
        help="Generate JSON summary output (default: both JSON and MD if not specified)",
    )
    parser.add_argument(
        "--markdown-out",
        action="store_true",
        help="Generate markdown summary output (default: both JSON and MD if not specified)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without executing",
    )
    parser.add_argument(
        "--api-drills",
        action="store_true",
        help="Generate API-level drill commands and payloads (legacy plan mode alias)",
    )
    parser.add_argument(
        "--api-live",
        action="store_true",
        help="Execute full API lifecycle against a live server",
    )
    parser.add_argument(
        "--plan",
        action="store_true",
        help="When used with --api-drills or --api-live, output example curl commands and payloads without sending them",
    )
    parser.add_argument(
        "--bearer-token",
        type=str,
        default=None,
        help="Bearer token for authenticated API drill requests (env: FERRUM_BEARER_TOKEN)",
    )
    parser.add_argument(
        "--drills",
        type=str,
        default=None,
        help="Comma-separated list of drills to run, e.g., D1,D4 (default: all)",
    )
    parser.add_argument(
        "--rate-limit-delay",
        type=float,
        default=1.0,
        help="Delay in seconds between API calls in live mode (default: 1.0)",
    )
    parser.add_argument(
        "--evidence-label",
        type=str,
        default="",
        help="Optional label to embed in evidence output",
    )
    parser.add_argument(
        "--probe-readyz-deep",
        action="store_true",
        help="Run a diagnostic probe sequence against /v1/readyz/deep",
    )
    parser.add_argument(
        "--probe-count",
        type=int,
        default=5,
        help="Number of readyz/deep probes to send (default: 5)",
    )
    parser.add_argument(
        "--probe-interval",
        type=int,
        default=10,
        help="Seconds between readyz/deep probes (default: 10)",
    )

    return parser.parse_args()


def main():
    args = parse_args()

    print("=" * 60)
    print("FerrumGate v1 — D1–D6 Local Drill Runner")
    print("=" * 60)
    print()
    print("IMPORTANT: This script does NOT complete G2/operator signoff.")
    print("           Operator review is still required.")
    print()

    output_dir = ensure_output_dir(args.output_dir)
    print(f"Output directory: {output_dir}")
    print(f"Skip cargo tests: {args.skip_cargo}")
    print(f"Server URL: {args.server_url or 'Not provided (no live server required)'}")
    print(f"API drills: {args.api_drills}")
    print(f"API live: {args.api_live}")
    print(f"Plan mode: {args.plan}")
    print()

    selected_drills = None
    if args.drills:
        selected_drills = set(d.strip().upper() for d in args.drills.split(","))
        print(f"Selected drills: {selected_drills}")

    if args.probe_readyz_deep:
        if not args.server_url:
            print("ERROR: --probe-readyz-deep requires --server-url")
            return 1
        print("=" * 60)
        print("RUNNING READYZ/DEEP DIAGNOSTIC PROBE")
        print("=" * 60)
        if args.plan:
            probe_output_file = output_dir / "readyz_deep_probe_plan.md"
            lines = ["# /v1/readyz/deep Diagnostic Probe Plan\n\n"]
            lines.append(f"*Generated: {_now_rfc3339()}*\n")
            lines.append(f"*Server: {args.server_url}*\n")
            lines.append(f"*Probes: {args.probe_count} at {args.probe_interval}s intervals*\n\n")
            lines.append("Run the following command(s) on the target host:\n\n")
            url = f"{args.server_url}/v1/readyz/deep"
            for i in range(args.probe_count):
                lines.append(f"### Probe {i+1}\n")
                lines.extend(
                    _curl_block("GET", url, {"Content-Type": "application/json"}, None, True)
                )
                lines.append("")
                if i < args.probe_count - 1:
                    lines.append(f"sleep {args.probe_interval}\n")
            with open(probe_output_file, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))
            print(f"\n[PLAN MODE] Probe plan written to: {probe_output_file}")
            return 0
        json_file, md_file, _ = probe_readyz_deep(
            args.server_url,
            args.bearer_token,
            output_dir,
            probe_count=args.probe_count,
            probe_interval=args.probe_interval,
        )
        print(f"\nProbe JSON: {json_file}")
        print(f"Probe Markdown: {md_file}")
        return 0

    if args.dry_run and not (args.api_drills or args.api_live):
        print("[DRY RUN] Would execute the following drills:")
        for drill_name in DRILL_CARGO_TEST_MAPPING:
            key = drill_name.split()[0]
            if selected_drills is None or key in selected_drills:
                cargo_test = DRILL_CARGO_TEST_MAPPING[drill_name]
                print(f"  - {drill_name}: cargo test {' '.join(cargo_test['test_args'])}")
        print(f"  - Server smoke: {args.server_url or 'skipped'}")
        print(f"  - Output dir: {output_dir}")
        return 0

    results = {}

    # API mode (legacy --api-drills or new --api-live)
    api_mode = args.api_drills or args.api_live
    if api_mode:
        if not args.server_url:
            print("ERROR: --api-drills/--api-live requires --server-url")
            return 1
        print("=" * 60)
        print("RUNNING API-LEVEL DRILLS")
        print("=" * 60)
        api_results, api_file = run_api_drills(
            args.server_url,
            args.bearer_token,
            args.plan,
            output_dir,
            args.rate_limit_delay,
            selected_drills=selected_drills,
        )
        results.update(api_results)
        print(f"\nAPI drill output: {api_file}")
        if args.plan:
            print("[PLAN MODE] No live requests were sent.")
        # Skip cargo tests in API mode unless explicitly skipped
        args.skip_cargo = True

    # Run cargo tests if not skipped
    if not args.skip_cargo:
        print("\n" + "=" * 60)
        print("RUNNING D1–D6 CARGO TESTS")
        print("=" * 60)

        for drill_name, cargo_test in DRILL_CARGO_TEST_MAPPING.items():
            key = drill_name.split()[0]
            if selected_drills is not None and key not in selected_drills:
                continue
            result = run_cargo_tests(
                drill_name,
                cargo_test["test_args"],
                output_dir,
            )
            results[drill_name] = result
            status = "PASS" if result["success"] else "FAIL"
            print(f"\n>>> {drill_name}: {status} ({result['test_count']} tests)")

            # Brief pause between tests to avoid resource contention
            time.sleep(0.5)

    # Run optional server smoke
    server_smoke = None
    token_for_smoke = args.bearer_token or os.environ.get("FERRUM_BEARER_TOKEN", "")
    if args.server_url and not args.plan:
        print("\n" + "=" * 60)
        print("RUNNING SERVER SMOKE (OPTIONAL)")
        print("=" * 60)
        print(f"Server: {args.server_url}")
        server_smoke = run_server_smoke(args.server_url, token_for_smoke, output_dir)
        status = "PASS" if server_smoke.get("success") else "FAIL"
        print(f"\n>>> Server smoke: {status}")
    elif args.plan:
        print("\n[SKIPPED] Server smoke (plan mode; no live probes sent)")
    else:
        print("\n[SKIPPED] Server smoke (no --server-url provided)")

    # Generate output files
    print("\n" + "=" * 60)
    print("GENERATING OUTPUT FILES")
    print("=" * 60)

    output_files = []

    # Determine output format
    want_json = args.json_out or (not args.json_out and not args.markdown_out)
    want_md = args.markdown_out or (not args.json_out and not args.markdown_out)

    if want_json:
        json_file = generate_json_summary(
            results, output_dir, server_smoke, plan_mode=args.plan, evidence_label=args.evidence_label
        )
        output_files.append(json_file)
        print(f"Generated JSON: {json_file}")

    if want_md:
        md_file = generate_markdown_summary(
            results, output_dir, server_smoke, plan_mode=args.plan, evidence_label=args.evidence_label
        )
        output_files.append(md_file)
        print(f"Generated markdown: {md_file}")

    # Generate evidence skeletons from raw test output
    if not args.skip_cargo:
        combined_output = []
        for drill_name, result in results.items():
            output_file = result.get("output_file", "")
            if output_file and Path(output_file).exists():
                with open(output_file, "r", encoding="utf-8") as f:
                    combined_output.append(f"# {drill_name}\n{f.read()}")

        if combined_output:
            skeleton_md = generate_skeleton(
                "\n---\n".join(combined_output),
                output_dir,
                "d1-d6",
            )
            output_files.append(skeleton_md)
            print(f"Generated evidence skeleton: {skeleton_md}")

    # Summary
    print("\n" + "=" * 60)
    print("DRILL RUN SUMMARY")
    print("=" * 60)

    total = len(results)
    if args.plan:
        print(f"\nAPI drill plan items: {total}")
        print("No live requests were sent.")
    elif args.api_live:
        passed = sum(1 for r in results.values() if r.get("overall_status") == "passed")
        partial = sum(1 for r in results.values() if r.get("overall_status") == "partial")
        failed = sum(1 for r in results.values() if r.get("overall_status") not in ("passed", "partial"))
        print(f"\nTotal drills: {total}")
        print(f"Passed: {passed}")
        print(f"Partial: {partial}")
        print(f"Failed: {failed}")
    else:
        passed = sum(1 for r in results.values() if r.get("success"))
        failed = total - passed
        print(f"\nTotal drills: {total}")
        print(f"Passed: {passed}")
        print(f"Failed: {failed}")

    if server_smoke:
        smoke_status = "PASS" if server_smoke.get("success") else "FAIL"
        print(f"Server smoke: {smoke_status}")

    print(f"\nEvidence output: {output_dir}")
    print("\nOutput files:")
    for f in output_files:
        print(f"  - {f}")

    print("\n" + "=" * 60)
    print("IMPORTANT NOTES")
    print("=" * 60)
    print("- Evidence is labeled 'local/test-drill' — operator review REQUIRED")
    print("- No G2 gate is completed by this output")
    print("- No production pilot signoff is implied or granted")
    print("- Operator must review evidence per docs/implementation-path/58-*.md")
    print("=" * 60)

    if args.plan:
        return 0

    if args.api_live:
        failed_count = sum(
            1 for r in results.values()
            if r.get("overall_status") not in ("passed", "partial")
        )
        return 0 if failed_count == 0 else 1

    failed_count = sum(1 for r in results.values() if not r.get("success"))
    return 0 if failed_count == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
