#!/usr/bin/env python3
"""
D1–D6 Local Drill Runner for FerrumGate v1.

This script runs local evidence commands for compensation drill verification (D1–D6)
in an isolated test environment. It does NOT:
- Require a live ferrumd server (unless --server-url is provided for optional smoke)
- Complete any G2 gate or claim operator signoff
- Make a production-ready claim

Usage:
    # Run with defaults (output to /tmp/ferrum-drill-evidence/)
    python3 scripts/run_d1_d6_drills.py

    # Run with custom output directory
    python3 scripts/run_d1_d6_drills.py --output-dir /tmp/my-drill-evidence

    # Skip cargo tests (only generate skeleton from existing logs)
    python3 scripts/run_d1_d6_drills.py --skip-cargo

    # Run with optional server smoke (requires live server)
    python3 scripts/run_d1_d6_drills.py --server-url http://127.0.0.1:8080

    # JSON output only
    python3 scripts/run_d1_d6_drills.py --json-out

    # Markdown output only
    python3 scripts/run_d1_d6_drills.py --markdown-out

    # Help
    python3 scripts/run_d1_d6_drills.py --help

Evidence output is labeled "local/test-drill" and requires operator review.
Operator signoff per docs/implementation-path/59-pilot-readiness-evidence-packet.md.
"""

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.resolve()
DEFAULT_OUTPUT_DIR = Path("/tmp/ferrum-drill-evidence")
SKELETON_GENERATOR = REPO_ROOT / "scripts" / "generate_evidence_skeleton.py"

DISCLAIMER = """
> **⚠️  LOCAL/TEST-DRILL EVIDENCE — OPERATOR REVIEW REQUIRED**
>
> This evidence was generated by an automated local drill runner in a test environment.
> It does NOT complete any G2 gate, does NOT authorize a production pilot, and does NOT
> replace operator-executed drills in the target deployment environment.
>
> All evidence below requires operator review and explicit signoff per:
>   - D1-D6 drills: docs/implementation-path/58-workload-compensation-drill-evidence-template.md
>   - G2 gates: docs/implementation-path/59-pilot-readiness-evidence-packet.md
>
> **No production pilot signoff is implied or granted by this output.**
"""

DRILL_MAPPING = {
    "D1 (fs adapter)": {
        "crate": "ferrum-adapter-fs",
        "pattern": "test_rollback_",
        "description": "Filesystem adapter compensation/rollback tests",
        "cargo_args": ["-p", "ferrum-adapter-fs", "--", "test_rollback_"],
    },
    "D2 (git adapter)": {
        "crate": "ferrum-adapter-git",
        "pattern": "test_rollback_",
        "description": "Git adapter compensation/rollback tests",
        "cargo_args": ["-p", "ferrum-adapter-git", "--", "test_rollback_"],
    },
    "D3 (git remote fail-closed)": {
        "crate": "ferrum-adapter-git",
        "pattern": "test_git_push_rollback_returns_recovered_false_on_remote_deletion_failure",
        "description": "Git remote push fail-closed verification",
        "cargo_args": [
            "-p", "ferrum-adapter-git", "--",
            "test_git_push_rollback_returns_recovered_false_on_remote_deletion_failure",
        ],
    },
    "D4 (http adapter)": {
        "crate": "ferrum-adapter-http",
        "pattern": "test_compensate_|test_replay_",
        "description": "HTTP adapter compensation/replay tests",
        "cargo_args": ["-p", "ferrum-adapter-http", "--", "test_compensate_"],
    },
    "D5 (sqlite adapter)": {
        "crate": "ferrum-adapter-sqlite",
        "pattern": "rollback",
        "description": "SQLite adapter compensation/rollback tests",
        "cargo_args": ["-p", "ferrum-adapter-sqlite", "--", "rollback"],
    },
    "D6 (maildraft adapter)": {
        "crate": "ferrum-adapter-maildraft",
        "pattern": "rollback",
        "description": "Maildraft adapter compensation/rollback tests",
        "cargo_args": ["-p", "ferrum-adapter-maildraft", "--", "rollback"],
    },
}

DRILL_CARGO_TEST_MAPPING = {
    "D1 (fs adapter)": {
        "cargo_test": "ferrum-adapter-fs",
        "test_args": ["-p", "ferrum-adapter-fs", "--", "test_rollback_", "--test-threads=1"],
    },
    "D2 (git adapter)": {
        "cargo_test": "ferrum-adapter-git",
        "test_args": ["-p", "ferrum-adapter-git", "--", "test_rollback_", "--test-threads=1"],
    },
    "D3 (git remote fail-closed)": {
        "cargo_test": "ferrum-adapter-git",
        "test_args": [
            "-p", "ferrum-adapter-git", "--",
            "test_git_push_rollback_returns_recovered_false_on_remote_deletion_failure",
            "--test-threads=1",
        ],
    },
    "D4 (http adapter)": {
        "cargo_test": "ferrum-adapter-http",
        "test_args": ["-p", "ferrum-adapter-http", "--", "test_compensate_", "--test-threads=1"],
    },
    "D5 (sqlite adapter)": {
        "cargo_test": "ferrum-adapter-sqlite",
        "test_args": ["-p", "ferrum-adapter-sqlite", "--", "rollback", "--test-threads=1"],
    },
    "D6 (maildraft adapter)": {
        "cargo_test": "ferrum-adapter-maildraft",
        "test_args": ["-p", "ferrum-adapter-maildraft", "--", "rollback", "--test-threads=1"],
    },
}


def run_command(cmd, description, timeout=300, capture=True):
    """Run a command and return (success, output, returncode)."""
    print(f"\n{'=' * 60}")
    print(f"Running: {description}")
    print(f"Command: {' '.join(str(c) for c in cmd)}")
    print(f"{'=' * 60}")
    try:
        result = subprocess.run(
            cmd,
            shell=False,
            cwd=str(REPO_ROOT),
            capture_output=capture,
            text=True,
            timeout=timeout,
        )
        success = result.returncode == 0
        output = result.stdout + result.stderr if capture else ""
        return success, output, result.returncode
    except subprocess.TimeoutExpired:
        return False, f"Command timed out after {timeout}s", -1
    except Exception as e:
        return False, str(e), -1


def ensure_output_dir(output_dir):
    """Create output directory if it doesn't exist."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def run_cargo_tests(drill_name, cargo_args, output_dir):
    """Run cargo tests for a specific drill and capture output."""
    test_output_file = output_dir / f"{drill_name.replace(' ', '_').replace('(', '').replace(')', '')}_test_output.txt"
    combined_output = []

    cmd = ["cargo", "test", "--quiet"] + cargo_args

    success, output, rc = run_command(cmd, f"{drill_name} cargo tests", timeout=300)

    # Save raw output
    with open(test_output_file, "w", encoding="utf-8") as f:
        f.write(f"# {drill_name} Test Output\n")
        f.write(f"# Generated: {datetime.now().isoformat()}\n")
        f.write(f"# Command: {' '.join(str(c) for c in cmd)}\n")
        f.write(f"# Return code: {rc}\n")
        f.write(f"# Success: {success}\n")
        f.write("\n## STDOUT/STDERR:\n\n")
        f.write(output)

    combined_output.append(output)

    test_count = parse_test_count(output)

    # Drill fails if cargo succeeded but found zero tests (pattern matched nothing)
    if success and test_count == 0:
        success = False

    return {
        "drill": drill_name,
        "success": success,
        "returncode": rc,
        "output_file": str(test_output_file),
        "test_count": test_count,
    }


def parse_test_count(output):
    """Parse test count from cargo test output."""
    import re
    match = re.search(r"(\d+) passed", output)
    if match:
        return int(match.group(1))
    match = re.search(r"(\d+) failed", output)
    if match:
        return -int(match.group(1))
    return 0


def run_server_smoke(server_url, output_dir):
    """Run optional server smoke checks if server URL is provided."""
    smoke_output_file = output_dir / "server_smoke_output.txt"
    combined = []

    # Import and run check_pilot_readiness
    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    try:
        from check_pilot_readiness import (
            check_shallow_readiness,
            check_deep_readiness,
            check_functional_readiness,
            check_metrics_endpoint,
        )

        bearer_token = os.environ.get("FERRUMCTL_BEARER_TOKEN", "")

        results = {}
        for name, func in [
            ("shallow_readiness", check_shallow_readiness),
            ("deep_readiness", check_deep_readiness),
            ("functional_readiness", check_functional_readiness),
            ("metrics_endpoint", check_metrics_endpoint),
        ]:
            try:
                success, output = func(server_url, bearer_token)
                results[name] = {"success": success, "output": output[:500]}
            except Exception as e:
                results[name] = {"success": False, "output": str(e)}

        smoke_output = {
            "server_url": server_url,
            "timestamp": datetime.now().isoformat(),
            "results": results,
        }

        with open(smoke_output_file, "w", encoding="utf-8") as f:
            f.write(f"# Server Smoke Output\n")
            f.write(f"# Generated: {datetime.now().isoformat()}\n")
            f.write(f"# Server: {server_url}\n")
            f.write(json.dumps(smoke_output, indent=2))

        return {"success": True, "output_file": str(smoke_output_file), "results": results}

    except ImportError as e:
        return {"success": False, "output_file": str(smoke_output_file), "error": str(e)}


def generate_skeleton(content, output_dir, drill_type="d1-d6"):
    """Generate evidence skeleton using the existing generator script."""
    skeleton_output = output_dir / f"{drill_type}_evidence_skeleton.md"

    # Write content to temp file for skeleton generator
    temp_input = output_dir / f"{drill_type}_raw_input.txt"
    with open(temp_input, "w", encoding="utf-8") as f:
        f.write(content)

    cmd = [
        sys.executable,
        str(SKELETON_GENERATOR),
        "--type", drill_type,
        "--file", str(temp_input),
    ]

    success, output, rc = run_command(cmd, f"Generate {drill_type} evidence skeleton", timeout=30)

    if success:
        with open(skeleton_output, "w", encoding="utf-8") as f:
            f.write(output)
    else:
        # Fallback: write raw content with disclaimer
        with open(skeleton_output, "w", encoding="utf-8") as f:
            f.write(DISCLAIMER)
            f.write(f"\n\n# {drill_type.upper()} Evidence (Raw Output)\n\n")
            f.write(f"*Generated: {datetime.now().isoformat()}*\n\n")
            f.write("```\n")
            f.write(content[:10000])  # Truncate if too long
            f.write("\n```\n")

    return str(skeleton_output)


def generate_markdown_summary(results, output_dir, server_smoke=None, plan_mode=False):
    '''Generate markdown summary of drill results.'''
    md_file = output_dir / "drill_summary.md"

    with open(md_file, "w", encoding="utf-8") as f:
        f.write(DISCLAIMER)
        f.write("\n\n")
        f.write("# D1\u2013D6 Drill Runner Summary\n\n")
        f.write(f"*Generated: {datetime.now().isoformat()}*\n")
        f.write(f"*Repository: {REPO_ROOT}*\n")
        f.write(f"*Output directory: {output_dir}*\n\n")

        f.write("---\n\n")
        f.write("## Run Context\n\n")
        f.write("| Field | Value |\n")
        f.write("|-------|-------|\n")
        f.write(f"| Environment | Local/test-drill only |\n")
        f.write(f"| Generated | {datetime.now().isoformat()} |\n")
        f.write(f"| Evidence dir | {output_dir} |\n")
        f.write("| Server smoke | ")
        if plan_mode:
            f.write("Skipped in plan mode\n")
        elif server_smoke:
            f.write(f"PASS ({server_smoke.get('server_url', 'N/A')})\n")
        else:
            f.write("Not run (no --server-url provided)\n")
        f.write("\n---\n\n")

        if plan_mode:
            f.write("## Planned API Drills\n\n")
            f.write("| Drill | Status | Notes |\n")
            f.write("|-------|--------|-------|\n")
            for drill_name, result in results.items():
                f.write(f"| {drill_name} | Planned | API commands generated, not executed |\n")
            f.write("\n---\n\n")
            f.write("> **Note**: The full governance lifecycle (intent-compile \u2192 proposal-evaluate \u2192 ")
            f.write("capability-mint \u2192 execution-authorize) is not fully automated by this script. ")
            f.write("Operator must complete preceding steps before executing any generated commands.\n")
        else:
            f.write("## Drill Results\n\n")
            f.write("| Drill | Tests Passed | Output File |\n")
            f.write("|-------|--------------|-------------|\n")

            for drill_name, result in results.items():
                test_count = result.get("test_count", 0)
                output_file = Path(result.get("output_file", "")).name
                status = "\u2705" if result.get("success") else "\u274c"
                f.write(f"| {status} {drill_name} | {test_count} | `{output_file}` |\n")

        f.write("\n---\n\n")

        f.write("## Evidence Files\n\n")
        for drill_name, result in results.items():
            output_file = result.get("output_file", "")
            if output_file:
                f.write(f"- `{output_file}`\n")

        if server_smoke and server_smoke.get("output_file"):
            f.write(f"- `{server_smoke['output_file']}`\n")

        f.write("\n---\n\n")

        f.write("## Limitations / Operator Follow-Up\n\n")
        f.write("- D1\u2013D6 evidence is adapter-level test evidence, not full end-to-end operator drills.\n")
        f.write("- D3 confirms fail-closed behavior at adapter level; operator must evaluate target remote branch protection.\n")
        f.write("- D4 did not exercise a live external HTTP service.\n")
        f.write("- Signature fields remain blank until operator reviews evidence and signs per docs 58/59.\n")
        f.write("- No production pilot signoff is implied or granted.\n")

        f.write("\n---\n\n")
        f.write("*Generated by run_d1_d6_drills.py \u2014 operator review required before use.*\n")

    return str(md_file)

def generate_json_summary(results, output_dir, server_smoke=None, plan_mode=False):
    """Generate JSON summary of drill results."""
    json_file = output_dir / "drill_summary.json"

    summary = {
        "generated": datetime.now().isoformat(),
        "repository": str(REPO_ROOT),
        "output_dir": str(output_dir),
        "disclaimer": "LOCAL/TEST-DRILL EVIDENCE — OPERATOR REVIEW REQUIRED",
        "run_context": {
            "environment": "local/test-drill only",
            "plan_mode": plan_mode,
            "server_smoke": server_smoke.get("server_url") if server_smoke else None,
            "server_smoke_passed": server_smoke.get("success") if server_smoke else None,
        },
        "drill_results": {},
        "evidence_files": [],
    }

    for drill_name, result in results.items():
        if plan_mode:
            summary["drill_results"][drill_name] = {
                "planned": True,
                "test_count": 0,
                "returncode": 0,
                "output_file": result.get("output_file", ""),
            }
        else:
            summary["drill_results"][drill_name] = {
                "success": result.get("success", False),
                "test_count": result.get("test_count", 0),
                "returncode": result.get("returncode", -1),
                "output_file": result.get("output_file", ""),
            }
        if result.get("output_file"):
            summary["evidence_files"].append(result["output_file"])

    if server_smoke and server_smoke.get("output_file"):
        summary["evidence_files"].append(server_smoke["output_file"])

    with open(json_file, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    return str(json_file)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Run D1–D6 local evidence drills for FerrumGate v1.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run all drills with defaults
  python3 scripts/run_d1_d6_drills.py

  # Skip cargo tests, only generate skeleton from existing logs
  python3 scripts/run_d1_d6_drills.py --skip-cargo

  # Run with optional server smoke
  python3 scripts/run_d1_d6_drills.py --server-url http://127.0.0.1:8080

  # Custom output directory
  python3 scripts/run_d1_d6_drills.py --output-dir /tmp/my-drill-evidence

  # JSON output only
  python3 scripts/run_d1_d6_drills.py --json-out --skip-cargo

  # API-level drill plan (dry-run)
  python3 scripts/run_d1_d6_drills.py --api-drills --plan --server-url http://127.0.0.1:8080

IMPORTANT:
  This script does NOT complete G2/operator signoff.
  Operator review and explicit signoff is still required.
  See: docs/implementation-path/59-pilot-readiness-evidence-packet.md
        """,
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory for evidence (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--skip-cargo",
        action="store_true",
        help="Skip cargo test execution (use with --server-url for smoke only)",
    )
    parser.add_argument(
        "--server-url",
        type=str,
        default=None,
        help="Optional: FerrumGate server URL for readiness smoke or API drills",
    )
    parser.add_argument(
        "--json-out",
        action="store_true",
        help="Generate JSON summary output (default: both JSON and MD if not specified)",
    )
    parser.add_argument(
        "--markdown-out",
        action="store_true",
        help="Generate markdown summary output (default: both JSON and MD if not specified)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without executing",
    )
    parser.add_argument(
        "--api-drills",
        action="store_true",
        help="Generate API-level drill commands and payloads instead of running cargo tests",
    )
    parser.add_argument(
        "--plan",
        action="store_true",
        help="When used with --api-drills, output example curl commands and payloads without sending them",
    )
    parser.add_argument(
        "--bearer-token",
        type=str,
        default=None,
        help="Bearer token for authenticated API drill requests (env: FERRUM_BEARER_TOKEN)",
    )

    return parser.parse_args()


API_DRILL_TEMPLATES = {
    "D1 (fs adapter)": {
        "intent_compile_payload": {
            "principal_id": "00000000-0000-0000-0000-000000000001",
            "title": "D1 FS Drill",
            "goal": "Write file /tmp/ferrum_drill_D1_1.txt for rollback verification",
            "raw_inputs": [],
            "requested_resource_scope": [],
            "metadata": {"drill": "D1", "adapter": "fs"},
        },
        "execute_payload": {"content": "D1.1 FileWrite drill content"},
        "adapter_notes": "FileWrite adapter uses payload.content as file content.",
    },
    "D2 (git adapter)": {
        "intent_compile_payload": {
            "principal_id": "00000000-0000-0000-0000-000000000001",
            "title": "D2 Git Drill",
            "goal": "Git commit in /path/to/test/repo for rollback verification",
            "raw_inputs": [],
            "requested_resource_scope": [],
            "metadata": {"drill": "D2", "adapter": "git"},
        },
        "execute_payload": {},
        "adapter_notes": "Git adapter execute payload is typically empty; operation is encoded in the contract target.",
    },
    "D3 (git remote fail-closed)": {
        "intent_compile_payload": {
            "principal_id": "00000000-0000-0000-0000-000000000001",
            "title": "D3 Git Remote Drill",
            "goal": "Git push to non-prod remote with fail-closed verification",
            "raw_inputs": [],
            "requested_resource_scope": [],
            "metadata": {"drill": "D3", "adapter": "git", "remote": "origin"},
        },
        "execute_payload": {},
        "adapter_notes": "Requires non-prod bare remote. Fail-closed verified via pre-receive hook.",
    },
    "D4 (http adapter)": {
        "intent_compile_payload": {
            "principal_id": "00000000-0000-0000-0000-000000000001",
            "title": "D4 HTTP Drill",
            "goal": "HTTP POST to test endpoint with idempotency-aware compensation",
            "raw_inputs": [],
            "requested_resource_scope": [],
            "metadata": {"drill": "D4", "adapter": "http"},
        },
        "execute_payload": {"body": "{\"drill\": \"D4 HTTP POST\"}"},
        "adapter_notes": "HTTP adapter supports POST/PUT/PATCH with idempotency key. Compensation plan must use http.replay_v1 operation.",
    },
    "D5 (sqlite adapter)": {
        "intent_compile_payload": {
            "principal_id": "00000000-0000-0000-0000-000000000001",
            "title": "D5 SQLite Drill",
            "goal": "SQLite DML insert with transaction rollback verification",
            "raw_inputs": [],
            "requested_resource_scope": [],
            "metadata": {"drill": "D5", "adapter": "sqlite"},
        },
        "execute_payload": {"sql": "INSERT INTO drill_table (id, value) VALUES (1, 'D5 drill')"},
        "adapter_notes": "SQLite adapter accepts payload with 'sql' field. DML uses SAVEPOINT; DDL uses schema capture.",
    },
    "D6 (maildraft adapter)": {
        "intent_compile_payload": {
            "principal_id": "00000000-0000-0000-0000-000000000001",
            "title": "D6 MailDraft Drill",
            "goal": "Create email draft with rollback verification",
            "raw_inputs": [],
            "requested_resource_scope": [],
            "metadata": {"drill": "D6", "adapter": "maildraft"},
        },
        "execute_payload": {
            "draft_id": "d6-drill-1",
            "from": "drill@example.com",
            "to": ["recipient@example.com"],
            "subject": "D6 drill",
            "body": "D6 maildraft compensation drill",
        },
        "adapter_notes": "MailDraft adapter accepts draft fields in execute payload. Supports create, update, delete operations.",
    },
}


def run_api_drills(server_url, bearer_token, plan_mode, output_dir):
    """Run or plan API-level D1-D6 drills against a live FerrumGate server."""
    token = bearer_token or os.environ.get("FERRUM_BEARER_TOKEN", "")
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    results = {}
    api_output_lines = []
    api_output_lines.append("# D1-D6 API Drill Commands")
    api_output_lines.append(f"*Generated: {datetime.now().isoformat()}*")
    api_output_lines.append(f"*Server: {server_url}*")
    api_output_lines.append(f"*Mode: {'PLAN (dry-run)' if plan_mode else 'LIVE'}*")
    api_output_lines.append("")
    api_output_lines.append("> **LIMITATION**: Full automated API drill execution requires the complete")
    api_output_lines.append("> intent-compile → proposal-evaluate → capability-mint → execution-authorize")
    api_output_lines.append("> lifecycle chain. This script generates the execute-phase payloads only.")
    api_output_lines.append("> Operator must perform the preceding governance steps manually or via ferrumctl.")
    api_output_lines.append("")

    for drill_name, template in API_DRILL_TEMPLATES.items():
        api_output_lines.append(f"## {drill_name}")
        api_output_lines.append("")
        api_output_lines.append(f"**Adapter notes**: {template['adapter_notes']}")
        api_output_lines.append("")

        # Step 1: Intent compile
        api_output_lines.append("### 1. Compile Intent")
        api_output_lines.append(f"```bash")
        api_output_lines.append(
            f"curl -s -X POST '{server_url}/v1/intents/compile' \\")
        if token:
            api_output_lines.append("  -H 'Authorization: Bearer $FERRUM_BEARER_TOKEN' \\")
        api_output_lines.append(f"  -H 'Content-Type: application/json' \\")
        payload_json = json.dumps(template["intent_compile_payload"], indent=2)
        # Indent payload lines for the curl command
        payload_lines = payload_json.split("\n")
        if len(payload_lines) == 1:
            api_output_lines.append(f"  -d '{payload_json}'")
        else:
            api_output_lines.append(f"  -d '{payload_lines[0]}")
            for line in payload_lines[1:-1]:
                api_output_lines.append(f"  {line}")
            api_output_lines.append(f"  {payload_lines[-1]}'")
        api_output_lines.append("```")
        api_output_lines.append("")

        # Step 2: Execute (payload only)
        api_output_lines.append("### 2. Execute Payload")
        api_output_lines.append(
            "Use this payload with POST /v1/executions/{execution_id}/execute after authorize+prepare:"
        )
        api_output_lines.append("```json")
        api_output_lines.append(json.dumps(template["execute_payload"], indent=2))
        api_output_lines.append("```")
        api_output_lines.append("")

        # If not plan mode, attempt a shallow probe
        if not plan_mode:
            try:
                import urllib.request
                req = urllib.request.Request(
                    f"{server_url}/v1/healthz",
                    method="GET",
                    headers=headers if token else {},
                )
                with urllib.request.urlopen(req, timeout=5) as resp:
                    health_ok = resp.status == 200
            except Exception as e:
                health_ok = False
                api_output_lines.append(f"*Shallow probe failed: {e}*")

            results[drill_name] = {
                "success": health_ok,
                "test_count": 1 if health_ok else 0,
                "returncode": 0 if health_ok else 1,
                "output_file": "",
            }
        else:
            results[drill_name] = {
                "planned": True,
                "test_count": 0,
                "returncode": 0,
                "output_file": "",
                "mode": "plan",
            }

    # Write API drill output
    api_output_file = output_dir / "api_drill_commands.md"
    with open(api_output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(api_output_lines))

    return results, str(api_output_file)


def main():
    args = parse_args()

    print("=" * 60)
    print("FerrumGate v1 — D1–D6 Local Drill Runner")
    print("=" * 60)
    print()
    print("IMPORTANT: This script does NOT complete G2/operator signoff.")
    print("           Operator review is still required.")
    print()

    output_dir = ensure_output_dir(args.output_dir)
    print(f"Output directory: {output_dir}")
    print(f"Skip cargo tests: {args.skip_cargo}")
    print(f"Server URL: {args.server_url or 'Not provided (no live server required)'}")
    print(f"API drills: {args.api_drills}")
    print()

    if args.dry_run and not args.api_drills:
        print("[DRY RUN] Would execute the following drills:")
        for drill_name in DRILL_CARGO_TEST_MAPPING:
            cargo_test = DRILL_CARGO_TEST_MAPPING[drill_name]
            print(f"  - {drill_name}: cargo test {' '.join(cargo_test['test_args'])}")
        print(f"  - Server smoke: {args.server_url or 'skipped'}")
        print(f"  - Output dir: {output_dir}")
        return 0

    results = {}

    # API drills mode
    if args.api_drills:
        if not args.server_url:
            print("ERROR: --api-drills requires --server-url")
            return 1
        print("=" * 60)
        print("RUNNING API-LEVEL DRILLS")
        print("=" * 60)
        api_results, api_file = run_api_drills(
            args.server_url,
            args.bearer_token,
            args.plan,
            output_dir,
        )
        results.update(api_results)
        print(f"\nAPI drill output: {api_file}")
        if args.plan:
            print("[PLAN MODE] No live requests were sent.")
        # Skip cargo tests in API mode unless explicitly skipped
        args.skip_cargo = True

    # Run cargo tests if not skipped
    if not args.skip_cargo:
        print("\n" + "=" * 60)
        print("RUNNING D1–D6 CARGO TESTS")
        print("=" * 60)

        for drill_name, cargo_test in DRILL_CARGO_TEST_MAPPING.items():
            result = run_cargo_tests(
                drill_name,
                cargo_test["test_args"],
                output_dir,
            )
            results[drill_name] = result
            status = "PASS" if result["success"] else "FAIL"
            print(f"\n>>> {drill_name}: {status} ({result['test_count']} tests)")

            # Brief pause between tests to avoid resource contention
            time.sleep(0.5)

    # Run optional server smoke
    server_smoke = None
    if args.server_url and not args.plan:
        print("\n" + "=" * 60)
        print("RUNNING SERVER SMOKE (OPTIONAL)")
        print("=" * 60)
        print(f"Server: {args.server_url}")
        server_smoke = run_server_smoke(args.server_url, output_dir)
        status = "PASS" if server_smoke.get("success") else "FAIL"
        print(f"\n>>> Server smoke: {status}")
    elif args.plan:
        print("\n[SKIPPED] Server smoke (plan mode; no live probes sent)")
    else:
        print("\n[SKIPPED] Server smoke (no --server-url provided)")

    # Generate output files
    print("\n" + "=" * 60)
    print("GENERATING OUTPUT FILES")
    print("=" * 60)

    output_files = []

    # Determine output format
    want_json = args.json_out or (not args.json_out and not args.markdown_out)
    want_md = args.markdown_out or (not args.json_out and not args.markdown_out)

    if want_json:
        json_file = generate_json_summary(results, output_dir, server_smoke, plan_mode=args.plan)
        output_files.append(json_file)
        print(f"Generated JSON: {json_file}")

    if want_md:
        md_file = generate_markdown_summary(results, output_dir, server_smoke, plan_mode=args.plan)
        output_files.append(md_file)
        print(f"Generated markdown: {md_file}")

    # Generate evidence skeletons from raw test output
    if not args.skip_cargo:
        combined_output = []
        for drill_name, result in results.items():
            output_file = result.get("output_file", "")
            if output_file and Path(output_file).exists():
                with open(output_file, "r", encoding="utf-8") as f:
                    combined_output.append(f"# {drill_name}\n{f.read()}")

        if combined_output:
            skeleton_md = generate_skeleton(
                "\n---\n".join(combined_output),
                output_dir,
                "d1-d6",
            )
            output_files.append(skeleton_md)
            print(f"Generated evidence skeleton: {skeleton_md}")

    # Summary
    print("\n" + "=" * 60)
    print("DRILL RUN SUMMARY")
    print("=" * 60)

    total = len(results)
    passed = sum(1 for r in results.values() if r.get("success"))
    failed = total - passed

    if args.plan:
        print(f"\nAPI drill plan items: {total}")
        print("No live requests were sent.")
    else:
        print(f"\nTotal drills: {total}")
        print(f"Passed: {passed}")
        print(f"Failed: {failed}")

    if server_smoke:
        smoke_status = "PASS" if server_smoke.get("success") else "FAIL"
        print(f"Server smoke: {smoke_status}")

    print(f"\nEvidence output: {output_dir}")
    print("\nOutput files:")
    for f in output_files:
        print(f"  - {f}")

    print("\n" + "=" * 60)
    print("IMPORTANT NOTES")
    print("=" * 60)
    print("- Evidence is labeled 'local/test-drill' — operator review REQUIRED")
    print("- No G2 gate is completed by this output")
    print("- No production pilot signoff is implied or granted")
    print("- Operator must review evidence per docs/implementation-path/58-*.md")
    print("=" * 60)

    if args.plan:
        return 0
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
