#!/usr/bin/env python3
"""
D1–D6 Local Drill Runner for FerrumGate v1.

This script runs local evidence commands for compensation drill verification (D1–D6)
in an isolated test environment. It does NOT:
- Require a live ferrumd server (unless --server-url is provided for optional smoke)
- Complete any G2 gate or claim operator signoff
- Make a production-ready claim

Usage:
    # Run with defaults (output to /tmp/ferrum-drill-evidence/)
    python3 scripts/run_d1_d6_drills.py

    # Run with custom output directory
    python3 scripts/run_d1_d6_drills.py --output-dir /tmp/my-drill-evidence

    # Skip cargo tests (only generate skeleton from existing logs)
    python3 scripts/run_d1_d6_drills.py --skip-cargo

    # Run with optional server smoke (requires live server)
    python3 scripts/run_d1_d6_drills.py --server-url http://127.0.0.1:8080

    # JSON output only
    python3 scripts/run_d1_d6_drills.py --json-out

    # Markdown output only
    python3 scripts/run_d1_d6_drills.py --markdown-out

    # Help
    python3 scripts/run_d1_d6_drills.py --help

Evidence output is labeled "local/test-drill" and requires operator review.
Operator signoff per docs/implementation-path/59-pilot-readiness-evidence-packet.md.
"""

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.resolve()
DEFAULT_OUTPUT_DIR = Path("/tmp/ferrum-drill-evidence")
SKELETON_GENERATOR = REPO_ROOT / "scripts" / "generate_evidence_skeleton.py"

DISCLAIMER = """
> **⚠️  LOCAL/TEST-DRILL EVIDENCE — OPERATOR REVIEW REQUIRED**
>
> This evidence was generated by an automated local drill runner in a test environment.
> It does NOT complete any G2 gate, does NOT authorize a production pilot, and does NOT
> replace operator-executed drills in the target deployment environment.
>
> All evidence below requires operator review and explicit signoff per:
>   - D1-D6 drills: docs/implementation-path/58-workload-compensation-drill-evidence-template.md
>   - G2 gates: docs/implementation-path/59-pilot-readiness-evidence-packet.md
>
> **No production pilot signoff is implied or granted by this output.**
"""

DRILL_MAPPING = {
    "D1 (fs adapter)": {
        "crate": "ferrum-adapter-fs",
        "pattern": "test_rollback_",
        "description": "Filesystem adapter compensation/rollback tests",
        "cargo_args": ["-p", "ferrum-adapter-fs", "--", "test_rollback_"],
    },
    "D2 (git adapter)": {
        "crate": "ferrum-adapter-git",
        "pattern": "test_rollback_",
        "description": "Git adapter compensation/rollback tests",
        "cargo_args": ["-p", "ferrum-adapter-git", "--", "test_rollback_"],
    },
    "D3 (git remote fail-closed)": {
        "crate": "ferrum-adapter-git",
        "pattern": "test_git_push_rollback_returns_recovered_false_on_remote_deletion_failure",
        "description": "Git remote push fail-closed verification",
        "cargo_args": [
            "-p", "ferrum-adapter-git", "--",
            "test_git_push_rollback_returns_recovered_false_on_remote_deletion_failure",
        ],
    },
    "D4 (http adapter)": {
        "crate": "ferrum-adapter-http",
        "pattern": "test_compensate_|test_replay_",
        "description": "HTTP adapter compensation/replay tests",
        "cargo_args": ["-p", "ferrum-adapter-http", "--", "test_compensate_"],
    },
    "D5 (sqlite adapter)": {
        "crate": "ferrum-adapter-sqlite",
        "pattern": "rollback",
        "description": "SQLite adapter compensation/rollback tests",
        "cargo_args": ["-p", "ferrum-adapter-sqlite", "--", "rollback"],
    },
    "D6 (maildraft adapter)": {
        "crate": "ferrum-adapter-maildraft",
        "pattern": "rollback",
        "description": "Maildraft adapter compensation/rollback tests",
        "cargo_args": ["-p", "ferrum-adapter-maildraft", "--", "rollback"],
    },
}

DRILL_CARGO_TEST_MAPPING = {
    "D1 (fs adapter)": {
        "cargo_test": "ferrum-adapter-fs",
        "test_args": ["-p", "ferrum-adapter-fs", "--", "test_rollback_", "--test-threads=1"],
    },
    "D2 (git adapter)": {
        "cargo_test": "ferrum-adapter-git",
        "test_args": ["-p", "ferrum-adapter-git", "--", "test_rollback_", "--test-threads=1"],
    },
    "D3 (git remote fail-closed)": {
        "cargo_test": "ferrum-adapter-git",
        "test_args": [
            "-p", "ferrum-adapter-git", "--",
            "test_git_push_rollback_returns_recovered_false_on_remote_deletion_failure",
            "--test-threads=1",
        ],
    },
    "D4 (http adapter)": {
        "cargo_test": "ferrum-adapter-http",
        "test_args": ["-p", "ferrum-adapter-http", "--", "test_compensate_", "--test-threads=1"],
    },
    "D5 (sqlite adapter)": {
        "cargo_test": "ferrum-adapter-sqlite",
        "test_args": ["-p", "ferrum-adapter-sqlite", "--", "rollback", "--test-threads=1"],
    },
    "D6 (maildraft adapter)": {
        "cargo_test": "ferrum-adapter-maildraft",
        "test_args": ["-p", "ferrum-adapter-maildraft", "--", "rollback", "--test-threads=1"],
    },
}


def run_command(cmd, description, timeout=300, capture=True):
    """Run a command and return (success, output, returncode)."""
    print(f"\n{'=' * 60}")
    print(f"Running: {description}")
    print(f"Command: {' '.join(str(c) for c in cmd)}")
    print(f"{'=' * 60}")
    try:
        result = subprocess.run(
            cmd,
            shell=False,
            cwd=str(REPO_ROOT),
            capture_output=capture,
            text=True,
            timeout=timeout,
        )
        success = result.returncode == 0
        output = result.stdout + result.stderr if capture else ""
        return success, output, result.returncode
    except subprocess.TimeoutExpired:
        return False, f"Command timed out after {timeout}s", -1
    except Exception as e:
        return False, str(e), -1


def ensure_output_dir(output_dir):
    """Create output directory if it doesn't exist."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def run_cargo_tests(drill_name, cargo_args, output_dir):
    """Run cargo tests for a specific drill and capture output."""
    test_output_file = output_dir / f"{drill_name.replace(' ', '_').replace('(', '').replace(')', '')}_test_output.txt"
    combined_output = []

    cmd = ["cargo", "test", "--quiet"] + cargo_args

    success, output, rc = run_command(cmd, f"{drill_name} cargo tests", timeout=300)

    # Save raw output
    with open(test_output_file, "w", encoding="utf-8") as f:
        f.write(f"# {drill_name} Test Output\n")
        f.write(f"# Generated: {datetime.now().isoformat()}\n")
        f.write(f"# Command: {' '.join(str(c) for c in cmd)}\n")
        f.write(f"# Return code: {rc}\n")
        f.write(f"# Success: {success}\n")
        f.write("\n## STDOUT/STDERR:\n\n")
        f.write(output)

    combined_output.append(output)

    test_count = parse_test_count(output)

    # Drill fails if cargo succeeded but found zero tests (pattern matched nothing)
    if success and test_count == 0:
        success = False

    return {
        "drill": drill_name,
        "success": success,
        "returncode": rc,
        "output_file": str(test_output_file),
        "test_count": test_count,
    }


def parse_test_count(output):
    """Parse test count from cargo test output."""
    import re
    match = re.search(r"(\d+) passed", output)
    if match:
        return int(match.group(1))
    match = re.search(r"(\d+) failed", output)
    if match:
        return -int(match.group(1))
    return 0


def run_server_smoke(server_url, output_dir):
    """Run optional server smoke checks if server URL is provided."""
    smoke_output_file = output_dir / "server_smoke_output.txt"
    combined = []

    # Import and run check_pilot_readiness
    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    try:
        from check_pilot_readiness import (
            check_shallow_readiness,
            check_deep_readiness,
            check_functional_readiness,
            check_metrics_endpoint,
        )

        bearer_token = os.environ.get("FERRUMCTL_BEARER_TOKEN", "")

        results = {}
        for name, func in [
            ("shallow_readiness", check_shallow_readiness),
            ("deep_readiness", check_deep_readiness),
            ("functional_readiness", check_functional_readiness),
            ("metrics_endpoint", check_metrics_endpoint),
        ]:
            try:
                success, output = func(server_url, bearer_token)
                results[name] = {"success": success, "output": output[:500]}
            except Exception as e:
                results[name] = {"success": False, "output": str(e)}

        smoke_output = {
            "server_url": server_url,
            "timestamp": datetime.now().isoformat(),
            "results": results,
        }

        with open(smoke_output_file, "w", encoding="utf-8") as f:
            f.write(f"# Server Smoke Output\n")
            f.write(f"# Generated: {datetime.now().isoformat()}\n")
            f.write(f"# Server: {server_url}\n")
            f.write(json.dumps(smoke_output, indent=2))

        return {"success": True, "output_file": str(smoke_output_file), "results": results}

    except ImportError as e:
        return {"success": False, "output_file": str(smoke_output_file), "error": str(e)}


def generate_skeleton(content, output_dir, drill_type="d1-d6"):
    """Generate evidence skeleton using the existing generator script."""
    skeleton_output = output_dir / f"{drill_type}_evidence_skeleton.md"

    # Write content to temp file for skeleton generator
    temp_input = output_dir / f"{drill_type}_raw_input.txt"
    with open(temp_input, "w", encoding="utf-8") as f:
        f.write(content)

    cmd = [
        sys.executable,
        str(SKELETON_GENERATOR),
        "--type", drill_type,
        "--file", str(temp_input),
    ]

    success, output, rc = run_command(cmd, f"Generate {drill_type} evidence skeleton", timeout=30)

    if success:
        with open(skeleton_output, "w", encoding="utf-8") as f:
            f.write(output)
    else:
        # Fallback: write raw content with disclaimer
        with open(skeleton_output, "w", encoding="utf-8") as f:
            f.write(DISCLAIMER)
            f.write(f"\n\n# {drill_type.upper()} Evidence (Raw Output)\n\n")
            f.write(f"*Generated: {datetime.now().isoformat()}*\n\n")
            f.write("```\n")
            f.write(content[:10000])  # Truncate if too long
            f.write("\n```\n")

    return str(skeleton_output)


def generate_markdown_summary(results, output_dir, server_smoke=None):
    """Generate markdown summary of drill results."""
    md_file = output_dir / "drill_summary.md"

    with open(md_file, "w", encoding="utf-8") as f:
        f.write(DISCLAIMER)
        f.write("\n\n")
        f.write("# D1–D6 Drill Runner Summary\n\n")
        f.write(f"*Generated: {datetime.now().isoformat()}*\n")
        f.write(f"*Repository: {REPO_ROOT}*\n")
        f.write(f"*Output directory: {output_dir}*\n\n")

        f.write("---\n\n")
        f.write("## Run Context\n\n")
        f.write("| Field | Value |\n")
        f.write("|-------|-------|\n")
        f.write(f"| Environment | Local/test-drill only |\n")
        f.write(f"| Generated | {datetime.now().isoformat()} |\n")
        f.write(f"| Evidence dir | {output_dir} |\n")
        f.write("| Server smoke | ")
        if server_smoke:
            f.write(f"PASS ({server_smoke.get('server_url', 'N/A')})\n")
        else:
            f.write("Not run (no --server-url provided)\n")
        f.write("\n---\n\n")

        f.write("## Drill Results\n\n")
        f.write("| Drill | Tests Passed | Output File |\n")
        f.write("|-------|--------------|-------------|\n")

        for drill_name, result in results.items():
            test_count = result.get("test_count", 0)
            output_file = Path(result.get("output_file", "")).name
            status = "✅" if result.get("success") else "❌"
            f.write(f"| {status} {drill_name} | {test_count} | `{output_file}` |\n")

        f.write("\n---\n\n")

        f.write("## Evidence Files\n\n")
        for drill_name, result in results.items():
            output_file = result.get("output_file", "")
            if output_file:
                f.write(f"- `{output_file}`\n")

        if server_smoke and server_smoke.get("output_file"):
            f.write(f"- `{server_smoke['output_file']}`\n")

        f.write("\n---\n\n")

        f.write("## Limitations / Operator Follow-Up\n\n")
        f.write("- D1–D6 evidence is adapter-level test evidence, not full end-to-end operator drills.\n")
        f.write("- D3 confirms fail-closed behavior at adapter level; operator must evaluate target remote branch protection.\n")
        f.write("- D4 did not exercise a live external HTTP service.\n")
        f.write("- Signature fields remain blank until operator reviews evidence and signs per docs 58/59.\n")
        f.write("- No production pilot signoff is implied or granted.\n")

        f.write("\n---\n\n")
        f.write("*Generated by run_d1_d6_drills.py — operator review required before use.*\n")

    return str(md_file)


def generate_json_summary(results, output_dir, server_smoke=None):
    """Generate JSON summary of drill results."""
    json_file = output_dir / "drill_summary.json"

    summary = {
        "generated": datetime.now().isoformat(),
        "repository": str(REPO_ROOT),
        "output_dir": str(output_dir),
        "disclaimer": "LOCAL/TEST-DRILL EVIDENCE — OPERATOR REVIEW REQUIRED",
        "run_context": {
            "environment": "local/test-drill only",
            "server_smoke": server_smoke.get("server_url") if server_smoke else None,
            "server_smoke_passed": server_smoke.get("success") if server_smoke else None,
        },
        "drill_results": {},
        "evidence_files": [],
    }

    for drill_name, result in results.items():
        summary["drill_results"][drill_name] = {
            "success": result.get("success", False),
            "test_count": result.get("test_count", 0),
            "returncode": result.get("returncode", -1),
            "output_file": result.get("output_file", ""),
        }
        if result.get("output_file"):
            summary["evidence_files"].append(result["output_file"])

    if server_smoke and server_smoke.get("output_file"):
        summary["evidence_files"].append(server_smoke["output_file"])

    with open(json_file, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    return str(json_file)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Run D1–D6 local evidence drills for FerrumGate v1.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run all drills with defaults
  python3 scripts/run_d1_d6_drills.py

  # Skip cargo tests, only generate skeleton from existing logs
  python3 scripts/run_d1_d6_drills.py --skip-cargo

  # Run with optional server smoke
  python3 scripts/run_d1_d6_drills.py --server-url http://127.0.0.1:8080

  # Custom output directory
  python3 scripts/run_d1_d6_drills.py --output-dir /tmp/my-drill-evidence

  # JSON output only
  python3 scripts/run_d1_d6_drills.py --json-out --skip-cargo

IMPORTANT:
  This script does NOT complete G2/operator signoff.
  Operator review and explicit signoff is still required.
  See: docs/implementation-path/59-pilot-readiness-evidence-packet.md
        """,
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory for evidence (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--skip-cargo",
        action="store_true",
        help="Skip cargo test execution (use with --server-url for smoke only)",
    )
    parser.add_argument(
        "--server-url",
        type=str,
        default=None,
        help="Optional: FerrumGate server URL for readiness smoke (requires live server)",
    )
    parser.add_argument(
        "--json-out",
        action="store_true",
        help="Generate JSON summary output (default: both JSON and MD if not specified)",
    )
    parser.add_argument(
        "--markdown-out",
        action="store_true",
        help="Generate markdown summary output (default: both JSON and MD if not specified)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without executing",
    )

    return parser.parse_args()


def main():
    args = parse_args()

    print("=" * 60)
    print("FerrumGate v1 — D1–D6 Local Drill Runner")
    print("=" * 60)
    print()
    print("IMPORTANT: This script does NOT complete G2/operator signoff.")
    print("           Operator review is still required.")
    print()

    output_dir = ensure_output_dir(args.output_dir)
    print(f"Output directory: {output_dir}")
    print(f"Skip cargo tests: {args.skip_cargo}")
    print(f"Server URL: {args.server_url or 'Not provided (no live server required)'}")
    print()

    if args.dry_run:
        print("[DRY RUN] Would execute the following drills:")
        for drill_name in DRILL_CARGO_TEST_MAPPING:
            cargo_test = DRILL_CARGO_TEST_MAPPING[drill_name]
            print(f"  - {drill_name}: cargo test {' '.join(cargo_test['test_args'])}")
        print(f"  - Server smoke: {args.server_url or 'skipped'}")
        print(f"  - Output dir: {output_dir}")
        return 0

    results = {}

    # Run cargo tests if not skipped
    if not args.skip_cargo:
        print("\n" + "=" * 60)
        print("RUNNING D1–D6 CARGO TESTS")
        print("=" * 60)

        for drill_name, cargo_test in DRILL_CARGO_TEST_MAPPING.items():
            result = run_cargo_tests(
                drill_name,
                cargo_test["test_args"],
                output_dir,
            )
            results[drill_name] = result
            status = "PASS" if result["success"] else "FAIL"
            print(f"\n>>> {drill_name}: {status} ({result['test_count']} tests)")

            # Brief pause between tests to avoid resource contention
            time.sleep(0.5)

    # Run optional server smoke
    server_smoke = None
    if args.server_url:
        print("\n" + "=" * 60)
        print("RUNNING SERVER SMOKE (OPTIONAL)")
        print("=" * 60)
        print(f"Server: {args.server_url}")
        server_smoke = run_server_smoke(args.server_url, output_dir)
        status = "PASS" if server_smoke.get("success") else "FAIL"
        print(f"\n>>> Server smoke: {status}")
    else:
        print("\n[SKIPPED] Server smoke (no --server-url provided)")

    # Generate output files
    print("\n" + "=" * 60)
    print("GENERATING OUTPUT FILES")
    print("=" * 60)

    output_files = []

    # Determine output format
    want_json = args.json_out or (not args.json_out and not args.markdown_out)
    want_md = args.markdown_out or (not args.json_out and not args.markdown_out)

    if want_json:
        json_file = generate_json_summary(results, output_dir, server_smoke)
        output_files.append(json_file)
        print(f"Generated JSON: {json_file}")

    if want_md:
        md_file = generate_markdown_summary(results, output_dir, server_smoke)
        output_files.append(md_file)
        print(f"Generated markdown: {md_file}")

    # Generate evidence skeletons from raw test output
    if not args.skip_cargo:
        combined_output = []
        for drill_name, result in results.items():
            output_file = result.get("output_file", "")
            if output_file and Path(output_file).exists():
                with open(output_file, "r", encoding="utf-8") as f:
                    combined_output.append(f"# {drill_name}\n{f.read()}")

        if combined_output:
            skeleton_md = generate_skeleton(
                "\n---\n".join(combined_output),
                output_dir,
                "d1-d6",
            )
            output_files.append(skeleton_md)
            print(f"Generated evidence skeleton: {skeleton_md}")

    # Summary
    print("\n" + "=" * 60)
    print("DRILL RUN SUMMARY")
    print("=" * 60)

    total = len(results)
    passed = sum(1 for r in results.values() if r.get("success"))
    failed = total - passed

    print(f"\nTotal drills: {total}")
    print(f"Passed: {passed}")
    print(f"Failed: {failed}")

    if server_smoke:
        smoke_status = "PASS" if server_smoke.get("success") else "FAIL"
        print(f"Server smoke: {smoke_status}")

    print(f"\nEvidence output: {output_dir}")
    print("\nOutput files:")
    for f in output_files:
        print(f"  - {f}")

    print("\n" + "=" * 60)
    print("IMPORTANT NOTES")
    print("=" * 60)
    print("- Evidence is labeled 'local/test-drill' — operator review REQUIRED")
    print("- No G2 gate is completed by this output")
    print("- No production pilot signoff is implied or granted")
    print("- Operator must review evidence per docs/implementation-path/58-*.md")
    print("=" * 60)

    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
