ALTER TABLE mfa_credentials
ADD COLUMN IF NOT EXISTS failed_attempts INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS locked_until TEXT,
ADD COLUMN IF NOT EXISTS last_failed_at TEXT,
ADD COLUMN IF NOT EXISTS lockout_count INTEGER DEFAULT 0;
