apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ferrumgate.fullname" . }}
  labels:
    {{- include "ferrumgate.labels" . | nindent 4 }}
type: Opaque
stringData:
  bearer-token: {{ .Values.secrets.bearerToken | quote }}
